### ISSUE TITLE
api-register-agent.sh not set ip manager in /var/ossec/etc/ossec.conf

### ISSUE THREAD

**Issue by goodccs** [wazuh/wazuh-api#10]
i register agent via sh api but  finsh with erros ->

2017/04/27 11:10:46 ossec-agentd(1237): ERROR: Invalid ip address: 'MANAGER_IP'.
2017/04/27 11:10:46 ossec-agentd(1202): ERROR: Configuration error at ''. Exiting.
2017/04/27 11:10:46 ossec-agentd(1215): ERROR: No client configured. Exiting.

server debian 8.7.1 and agents debian 8.7.1

after set ip server in /var/ossec/etc/ossec.conf  and var/ossec/bin/ossec-control restart

list agent it ok and active

**Comment by jesuslinares** [comment]
You need to setup the manager IP in the _ossec.conf_ of the agent:

**agent: /var/ossec/etc/ossec.conf** 
```
<ossec_config>
  <client>
    <server-ip>x.x.x.x</server-ip>
```
Then restart the agent:

`/var/ossec/bin/ossec-control restart`

Let me know if you get the error again.
Regards.
