### ISSUE TITLE
Broken sort by status

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-api#111]
Hi team,

When I try to sort by ***status*** in __GET /agents__ endpoint I always get the same unsorted result like this:

![captura](https://user-images.githubusercontent.com/10210567/41531778-ce03e344-72f4-11e8-9238-9c3872168cc3.PNG)

Regards,
Manu

**Comment by Lifka** [comment]
Thanks @manuasir for the report. The bug is fixed here: https://github.com/wazuh/wazuh/pull/810.

Regards,
Javi.

**Comment by manuasir** [comment]
Great job! Thanks @Lifka
