### ISSUE TITLE
Uppercase vs lowercase when sorting

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#112]
We have a problem sorting decoders, and I think using any list could be wrong too.
```
GET /decoders?sort=-name&limit=1&pretty" -s | grep name

 "name": "zeus",
```

```
GET /decoders?sort=name&limit=1&pretty" -s | grep name
    
"name": "Sysmon-EventID#1",
```

```
GET /decoders?limit=1&pretty" -s | grep name            

"name": "wazuh",
```

My bet is about "uppercase vs lowercase" cause they are "bigger"

Regards,
Jesús

**Comment by Lifka** [comment]
Thanks @jesusgn90 for the report!

The bug is fixed here: https://github.com/wazuh/wazuh/pull/814.
