### ISSUE TITLE
POST /agents with 'ANY' as ip-value crashes wazuh-modulesd

### ISSUE THREAD

**Issue by BurningNetel** [wazuh/wazuh-api#13]
Creating a new host via the REST api with ANY as ip-address will crash wazuh-modulesd.
ANY is an allowed value according to the [docs](https://documentation.wazuh.com/current/user-manual/api/reference.html#add).
Restarting this service does not fix the problem.

example:
```
$ curl -u foo:bar -k -X POST -d '{"name":"NewHost","ip":"ANY"}' -H 'Content-Type:application/json' "http://127.0.0.1:55000/agents?pretty"

{
   "error": 0,
   "data": "003"
}
```

To get wazuh-modulesd running again, i deleted the new entry from /var/ossec/etc/client.keys and restarted the service.

## Findings
I tried the POST /agents/:name [endpoint](https://documentation.wazuh.com/current/user-manual/api/reference.html#add-agent-quick-method) because it inserts ANY into the 'ip' -field.
This didn't crash the service.

The working entry in client.keys looks like this:
`003 myNewAgent any 42ab5b029044ab295a45837da5776570003b7166d32c1373fe54992beb4dd7d5`
The breaking entry looks like this:
`003 myNewAgent ANY 42ab5b029044ab295a45837da5776570003b7166d32c1373fe54992beb4dd7d5`

## Solution
I found [input_validation.js](https://github.com/wazuh/wazuh-api/blob/master/helpers/input_validation.js.
Removing the last entry from the 'ips' regex solves the problem, but only allows 'any' as input value.
I have not made a pull-request because i don't know if this is the best solution to the problem.

**Comment by jesuslinares** [comment]
Hi BurningNetel,

thanks for the detailed explanation. I fixed the issue (https://github.com/wazuh/wazuh-api/commit/aa903a7bd0f6f30a2962a1cd72bc0d5d0db57d70). Now the API accepts _ANY_ or _any_, but always it is written in the _client.keys_ as 'any'.

Thanks for your contribution.
Regards.
