### ISSUE TITLE
GET /agents/outdated not working as expected

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#135]
Hello team, look at the next responses:

```js
GET /
{
  "msg": "Welcome to Wazuh HIDS API",
  "api_version": "v3.3.1",
  "hostname": "osboxes",
  "timestamp": "Wed Jul 18 2018 12:03:42 GMT+0200 (CEST)"
}
```

```js
GET /agents/outdated
{
  "totalItems": 1,
  "items": [
    {
      "version": "Wazuh v3.4.0",
      "id": "006",
      "name": "jesus-dev-msi"
    }
  ]
}
```

The agent is higher than the manager but it says outdated.

- We should have a new route to retrieve those agents?
- We should hide those agents from /agents/outdated?

Regards,
Jesús

**Comment by jesusgn90** [comment]
Suggestion:

Add a new field for the agents. `version_status`, this new field would be three different values: `outdated`, `latest`, `higher_than_manager`. This way its an agent property and it can be filtered.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Yes @mgmacias95 , I think it should be a property from the agent and the only one thing your need is to add a new filter. 

```
GET /agents?version_status=equal
GET /agents?version_status=outdated
GET /agents?version_status=overdated
```

The current route `/agents/outdated` should be deprecated in further packages.

Since I know it's not as easy as add a new field, in the meantime we can create a new route for overdated agents and hiden them from the `/agents/outdated `route. Another simple solution is to add a filter for the` /agents/outdated` route. But definetively it should be an agent property and not a route.

**Comment by jesuslinares** [comment]
Solved here: https://github.com/wazuh/wazuh/pull/1381

Thanks.
