### ISSUE TITLE
Powershell Script IP Any

### ISSUE THREAD

**Issue by Justangatang** [wazuh/wazuh-api#136]
Hello,

Within the example Powershell script provided for the API connections, I can't figure out how to set the IP:ANY on an agent registration POST.

With Curl it works when set like this:
curl -u foo:bar -k -X POST -d '{"name":"NewHost","ip":"any"}'...

The powershell script has:
$response = req -method "POST" -resource "/agents" -params @{name=$agent_name}...

After $agent_name, how would you specify the IP as ANY?

Thanks!
Justin

**Comment by mgmacias95** [comment]
Hello Justin,

If you want to set the IP to any, you can use the [`PUT/agents/:agent_name`](https://documentation.wazuh.com/current/user-manual/api/reference.html#add-agent-quick-method) request instead of the `POST/agents` one.

The powershell line would be:
```powershell
$response = req -method "PUT" -resource "/agents/$($agent_name)" | ConvertFrom-Json
```

Best regards,
Marta

**Comment by Justangatang** [comment]
Hi Marta,

Thanks for the response, I've been using the PUT method since posting, but was hoping there was a way to do it with the POST method. Thank you!

**Comment by mgmacias95** [comment]
Hello Justin,

If you want to use the POST method, the line would be:

```powershell
$response = req -method "POST" -resource "/agents" -params @{name=$agent_name;ip="any"} | ConvertFrom-Json
```

Best regards,
Marta
