### ISSUE TITLE
REST-API: User Access Control needed

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh-api#148]
Hello,

### User Story
An API-user currently has **unchecked access** to all API-endpoints. If we want to integrate the API into a full-blown holistic opertional process, the API service must be exposed to a wider community of different kind of API-consumers. For example, the operational responsible department of the HIDS. They need to implement scripts where the API-credentials are encoded inside of the script quering the API for monitor or statistical purposes. Another department managing the agent life-cycle needs the access to the endpoints for the adding, updating and deletion of agents and its associated data. These endpoints are also available for the script user which just need access to some _HTTP-GET_ endpoints.

### User Acceptance Criteria
1. API user management allowing at least _three_ privilege levels:
1.1 only that endpoints are accessible which are needed for monitoring or statistical purposes
1.2 only hat endpoints are accessible which are needed for agent management 
1.3 full access to all endpoints
2. A more fine-grained access control might be implemented iteratively in later releases with respect of the access to endpoints with more _sensitive_ information which should not be exposed to everybody.

Thanks,
Jürgen

**Comment by JuanjiJG** [comment]
Hello @juergenc,

We're already working on a RBAC system for Wazuh. You can see the progress and make more suggestions to it on this link: https://github.com/wazuh/wazuh-api/issues/114

Thanks for your feedback, it's really appreciated!

Regards,
Juanjo

**Comment by jesuslinares** [comment]
@juergenc I will close this issue to continue the discussion in https://github.com/wazuh/wazuh-api/issues/114.

Thanks for your interest.
