### ISSUE TITLE
/manager/configuration doesn't show Vulnerability detector wodle configuration

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-api#149]
Hello team,

It looks like the `/manager/configuration` API call doesn't show the Vulnerability detector wodle configuration.

This is needed for the following issue: https://github.com/wazuh/wazuh-kibana-app/issues/822

Thanks for your time.

Regards,
Juanjo

**Comment by mgmacias95** [comment]
Done in https://github.com/wazuh/wazuh/pull/1453.
