### ISSUE TITLE
Wazuh API returned an error message. Error: Error getting configuration

### ISSUE THREAD

**Issue by kdslkdsaldsal** [wazuh/wazuh-api#15]
Hi,

currently running the following setup:

Debian jessie 8.7
Python 2.7.9
wazuh-manager 2.0-1jessie
wazuh-api: 2.0-1jessie

After following the complete setup tutorial everything working so far except i'm getting the following errors shown in the Kibana -> Wazuh -> Manager Dashboards "Status", "Ruleset" and "Configuration":

> Manager - Status: Wazuh API returned an error message. Error: Error getting configuration.
> Manager - Rules: Wazuh API returned an error message. Error: Error getting configuration.
> Manager - Configuration: Wazuh API returned an error message. Error: Error getting configuration.

When raising the debug level of the API the following logentries are found:

```
WazuhAPI 2017-06-04 16:01:22: ::ffff:xxx.yyy.zzz GET /rules
WazuhAPI 2017-06-04 16:01:22: CMD - Command: python args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/rules","arguments":{},"ossec_path":"/var/ossec"}
WazuhAPI 2017-06-04 16:01:22: CMD - Exit code: 0
WazuhAPI 2017-06-04 16:01:22: CMD - STDOUT:
---
{"message": "Error getting configuration.", "error": 1101}

---
WazuhAPI 2017-06-04 16:01:22: CMD - STDOUT: 59 bytes
WazuhAPI 2017-06-04 16:01:22: [::ffff:xxx.yyy.zzz] GET /rules/? - 200 - error: '1101'.

WazuhAPI 2017-06-04 16:04:20: ::ffff:xxx.yyy.zzz GET /manager/configuration
WazuhAPI 2017-06-04 16:04:20: CMD - Command: python args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/manager/configuration","arguments":{},"ossec_path":"/var/ossec"}
WazuhAPI 2017-06-04 16:04:20: CMD - STDOUT:
---
{"message": "Error getting configuration.", "error": 1101}

---
WazuhAPI 2017-06-04 16:04:20: CMD - Exit code: 0
WazuhAPI 2017-06-04 16:04:20: CMD - STDOUT: 59 bytes
WazuhAPI 2017-06-04 16:04:20: [::ffff:xxx.yyy.zzz] GET /manager/configuration? - 200 - error: '1101'.


WazuhAPI 2017-06-04 16:10:48: ::ffff:xxx.yyy.zzz GET /rules
WazuhAPI 2017-06-04 16:10:48: CMD - Command: python args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/rules","arguments":{"offset":"0","limit":"1"},"ossec_path":"/var/ossec"}
WazuhAPI 2017-06-04 16:10:49: CMD - Exit code: 0
WazuhAPI 2017-06-04 16:10:49: CMD - STDOUT:
---
{"message": "Error getting configuration.", "error": 1101}

---
WazuhAPI 2017-06-04 16:10:49: CMD - STDOUT: 59 bytes
WazuhAPI 2017-06-04 16:10:49: [::ffff:1xxx.yyy.zzz] GET /rules/?offset=0&limit=1 - 200 - error: '1101'.
WazuhAPI 2017-06-04 16:10:49: CMD - Exit code: 0
```

Those seems to be the only two URLs / calls causing such an error. All other API calls / URLS like ``/manager/logs?category=all&type_log=all&offset=0&limit=250 - 200 - error: '0'.`` are not throwing such errors.

Unfortunately its not really clear what ``Error getting configuration.`` means and how to solve this from user side.

Could it be possible to extend this message to have a little bit more context?

Anything what needs to be done here from user-side to fix this?

Thanks in advance for a reply.

**Comment by jesuslinares** [comment]
Hi @kdslkdsaldsal,

likely that error is due to the API doesn't have permissions to read `/var/ossec/etc/ossec.conf`. Please, check if the ossec user is able to read it.

> -rw-r-----  1 root  ossec 6.4K Jun  1 09:45 ossec.conf

We will improve the error message.

Let me know if it works.

**Comment by kdslkdsaldsal** [comment]
Hi,

and thanks for your reply. Those are the permissions on this file:

``-rw-r-----  1 root  ossec 6991 Jun  4 12:33 ossec.conf``

The API process runs with that process:

``ossec     9335  0.0  0.1 939584 38012 ?        Ssl  Jun04   0:07 /usr/bin/nodejs /var/ossec/api/app.js``

and when i'm firing the following command the content of the ossec.conf is shown:

``su -s /bin/bash -c "cat /var/ossec/etc/ossec.conf" ossec``

from what i can see this doesn't look like a Permission issue?

To make sure that i had used the correct command i have also used another user:

``su -s /bin/bash -c "cat /var/ossec/etc/ossec.conf" www-data``

which gives the expected ``cat: /var/ossec/etc/ossec.conf: Permission denied``

**Comment by jesuslinares** [comment]
Hi @kdslkdsaldsal,

well, in that case I think our parser is failing. Could you send us your ossec.conf?.

Also, you can do the following process to debug the error:

1. Go to `/var/ossec/api/framework/wazuh/configuration.py`
2. Replace lines [178-179](https://github.com/wazuh/wazuh-api/blob/stable/framework/wazuh/configuration.py#L178-L179):
```
    except:
        raise WazuhException(1101)
```
for:
```
    except Exception as e:
        raise WazuhException(1101, str(e))
```

In this way, we will see the exact error.

**Comment by kdslkdsaldsal** [comment]
Hey, great info. Thanks again. With this help / the changes in the configuration.py i was able to trace this down to the following error:

``{"error":1101,"message":"Error getting configuration: not well-formed (invalid token): line 204, column 2"}``

line 204 contains a commented out part:

```
<! --
  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/nginx/access.log</location>
  </localfile>

  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/nginx/error.log</location>
  </localfile>
-->
```

(Note the space between ``<!`` and ``--``). The wazuh-manager wasn't unhappy about this and parsed it without any error and started but it seems the API parser failed on this.

Should i keep this open or just close it as a PEBKAC?

Thanks again for your help

**Comment by jesuslinares** [comment]
Hi @kdslkdsaldsal,

finally we solve the error!. The API parser is stricter than OSSEC. Your comment is not valid in a [XML file](https://www.w3schools.com/xml/xml_syntax.asp). I'm going to close the issue because it is solved.

We will change the error to be more descriptive.

Thanks for the feedback.

**Comment by kdslkdsaldsal** [comment]
> I'm going to close the issue because it is solved.

Absolutely fine from my PoV, thanks again. 👍 

> We will change the error to be more descriptive.

Thanks here as well, i think that will definitely help if similar issues will arise in the future.
