### ISSUE TITLE
Decoding error on Framework/Wazuh-DB

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-api#150]
Hello team,

We've discovered a bug on the Wazuh framework. It's localized on this line: https://github.com/wazuh/wazuh/blob/master/framework/wazuh/wdb.py#L64

The `decode` method is using `ASCII` by default, instead of using UTF-8, so for example, when trying to fecth a package list with this one:
```
{"size":454,"scan_id":1268285079,"vendor":"Piotr Ożarowski <piotr@debian.org>","description":"universal character encoding detector for Python2","format":"deb","scan_time":"2018/08/31 10:17:08","section":"python","name":"python-chardet","priority":"optional","source":"chardet","version":"2.3.0-1","architecture":"all"}
```

The vendor name contains a special character that the ASCII table cannot decode. This throws a `2007` error.

The workaround is updating the `decode()` function call with `decode('utf-8')`, and then it works.

Regards,
Juanjo

**Comment by druizz90** [comment]
Hi team,

This PR [1331](https://github.com/wazuh/wazuh/pull/1331) solves this bug.

Best regards,

Demetrio.
