### ISSUE TITLE
Inventory summary

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-api#155]
This issue is related to the Wazuh mailing list thread [XFeQg2TYBak](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/wazuh/XFeQg2TYBak).

It would be very interesting to be able to get the inventory summary for more than one agent. This way, we could correlate useful information between agents like for example versions of a common package installed in all of them, or maybe which agents have a particular port opened.

We should discuss the best way to carry out this solution.

Regards.

**Comment by jesuslinares** [comment]
Hi @chemamartinez ,

It already exists as experimental:
```
GET /experimental/ciscat/results (Get CIS-CAT results)
GET /experimental/syscollector/hardware (Get hardware info of all agents)
GET /experimental/syscollector/netaddr (Get network address info of all agents)
GET /experimental/syscollector/netiface (Get network interface info of all agents)
GET /experimental/syscollector/netproto (Get network protocol info of all agents)
GET /experimental/syscollector/os (Get os info of all agents)
GET /experimental/syscollector/packages (Get packages info of all agents)
GET /experimental/syscollector/ports (Get ports info of all agents)
GET /experimental/syscollector/processes (Get processes info of all agents)
```

We need to improve the performance of this type of calls: https://github.com/wazuh/wazuh/issues/860

Thanks.
