### ISSUE TITLE
Can't install wazup-api fails on installing SQLite library

### ISSUE THREAD

**Issue by andel7** [wazuh/wazuh-api#16]
**According to documentation I executed:**

$curl -s -o install_api.sh https://raw.githubusercontent.com/wazuh/wazuh-api/2.0/install_api.sh \
> && bash ./install_api.sh download

**The output I get:**

### Wazuh API ###

Downloading API from https://github.com/wazuh/wazuh-api/archive/v2.0.tar.gz

Installing Wazuh API 2.0.0

Installing API ['/var/ossec/api'].

Installing SQLite library.
Error executing command: 'gcc -pipe -O2 -shared -fPIC -o /var/ossec/api/framework/lib/libsqlite3.so.0 framework/database/sqlite3.c'.

Exiting.

**Facts:**

OS Ubuntu 14.04.4 LTS
libsqlite3 package is installed 3.8.2-1ubuntu2.1
/var/ossec/api/framework/lib/ directory is empty
/var/ossec/api/framework/database directory doesn't exist
nodejs version is v6.11.0

**Comment by jesuslinares** [comment]
Hi @andel7,

it is a bug. Please, in `install_api.sh` file, change [the line](https://github.com/wazuh/wazuh-api/blob/v2.0/install_api.sh#L103):
`SOURCE="framework/database/sqlite3.c"`
to:
`SOURCE="$API_SOURCES/framework/database/sqlite3.c"`

We will fix it as soon as possible.

Remember that you can use the deb packages: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_deb.html#installing-wazuh-api

Thanks for the feedback.
