### ISSUE TITLE
FIM data in wazuh-db

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh-api#160]
Hi team.

For version 3.7 we are going to use wazuh-db to store the information generated by FIM, including the start and end of scan messages. So it is necessary to tell the API where this information is now being stored.

The FIM DDBB is now in `/var/ossec/queue/db/<agent-id>.db`
The table is called `metadata`, there are two text fields, `key` and `value`.

For example:

| KEY                     | VALUE      |
|-------------------------|------------|
| fim-db-start-first-scan | 1536848434 |
| fim-db-end-first-scan   | 1536848442 |
| fim-db-start-scan       | 1536848503 |
| fim-db-end-scan         | 1536848519 |

Regards.

**Comment by bah07** [comment]
We need to change the structure and create a new table to store this information. The name of the table will be `scan_info` and will contain the following fields:

| module       | first_start |  first_end | start_scan | end_scan   | fim_first_check | fim_second_check | fim_third_check |
|--------------|-------------|:----------:|-----------:|------------|-----------------|------------------|-----------------|
| fim          | 1538388326  | 1538388336 | 1538388062 | 1538388072 | 1538388326      | 1538388226       | 1538388125      |
| syscollector | 1538388320  | 1538388350 | 1538388920 | 1538388950 | NULL            | NULL             | NULL            |

This issue depends of [#1493](https://github.com/wazuh/wazuh/pull/1493)

**Comment by jesuslinares** [comment]
Done: https://github.com/wazuh/wazuh/pull/1449
