### ISSUE TITLE
empty lines in clients.keys will break the agent add endpoint

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-api#17]
Steps to replicate:

1. Have empty line in `clients.keys`
2. Attempt to add an agent via the API

```bash
$ curl -u user:pass -k -X POST -d 'name=MyAgent&ip=1.2.3.4' http://API_HOST:55000/agents
{"error":1000,"message":"Wazuh-Python Internal Error: invalid literal for int() with base 10: ''"}
```

Issue is located at https://github.com/wazuh/wazuh-api/blob/26625953854ff9a3cf49523e0555da6de145a6ea/framework/wazuh/agent.py#L470

The code on line 465 fails to filter out empty lines ending with line 470 trying to do `int('\n')`

**Comment by jesuslinares** [comment]
Hi,

I'm going to review it. I let you know when it is fixed.

Thanks!!

**Comment by jesuslinares** [comment]
I was not able to reply your issue:

```
$ /var/ossec/etc# ls -lah | grep client.keys
-rw-r-----  1 ossec ossec    0 Jul 28 14:50 client.keys
$ cat client.keys
$ curl -u foo:bar -k -X POST -d 'name=MyAgent&ip=1.2.3.4' http://localhost:55000/agents?pretty
{
   "error": 0,
   "data": "001"
}
```

Please, let us know the version of:

- Manager
- API
- Python

Thanks.
Regards.

**Comment by rossengeorgiev** [comment]
Try

```
001 agent1 any key

005 agent2 any key
```

**Comment by jesuslinares** [comment]
Fixed: https://github.com/wazuh/wazuh-api/commit/67b2fbf6263635bcfbea6cfff8c637add985b7bc

```
$ cat client.keys

$ curl -u foo:bar -k -X POST -d 'name=MyAgent&ip=1.2.3.4' http://localhost:55000/agents?pretty
{
   "error": 1000,
   "message": "Wazuh-Python Internal Error: invalid literal for int() with base 10: ''"
}
```

```
$ curl -u foo:bar -k -X POST -d 'name=MyAgent&ip=1.2.3.4' http://localhost:55000/agents?pretty
{
   "error": 0,
   "data": "001"
}
$ cat client.keys

001 MyAgent 1.2.3.4 f9b6a353316d56c06c0f02ae57bcf86f1a6fc746298badc8008e5e905631a1b7
```

It will be released with Wazuh API v2.1.0 (soon).

Thanks for the feedback!
Regards.

**Comment by snaow** [comment]
@rossengeorgiev thanks for your continuous feedback and catches, they help a lot and we will be happy to solve everything you detect for us.
: D

**Comment by rossengeorgiev** [comment]
Thanks! Keep up the good work
