### ISSUE TITLE
Error auth on API

### ISSUE THREAD

**Issue by santi10** [wazuh/wazuh-api#18]
HI, 

I have this error:

> root@wazuh01:/var/ossec/api/configuration/auth# sudo node htpasswd -c user wazuh
path.js:1142
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1142:25)
    at startup (bootstrap_node.js:127:32)
    at bootstrap_node.js:504:3

I have install nodejs and wazuh-api too wazuh-manager

Can you to do, please?

Thx

**Comment by vikman90** [comment]
Hi @santi10,

please tell us what OS are you using so we could try to reproduce this issue.

Thank you for reporting.
Best regards.

**Comment by santi10** [comment]
Hi,

Ubuntu 16.04 but This is error is the firts of installation. I didn't get to work yet.


thx

**Comment by BraulioV** [comment]
Hi @santi10,

I was trying to reproduce your error, but it works perfectly on my machine. Could you tell me which version of Node.js it's installed on your machine?.

Thank you.
Best regards.

**Comment by santi10** [comment]
Yes, the version nodejs is 6.11.2

Thanks in advance

**Comment by santi10** [comment]
Hi Braulio,

Yes, I followed that and I don't know why its is fail

Thx

**Comment by BraulioV** [comment]
Hi @santi10 ,

it's possible that `htpasswd` is failing. 

```
# cd /var/ossec/api/node_modules
# rm -rf *
# cd ..
# npm install
```
After that, please, check if `htpasswd@2.4.0` appears. Then, try to execute ` sudo node htpasswd -c user wazuh`again.

Thank you.
Regards.

**Comment by santi10** [comment]
Hi Braulio,

I did that and I had same result (fail)

You can see the version htpassed


htpasswd@2.4.0 node_modules/htpasswd
├── apache-md5@1.1.2
├── commander@2.11.0
├── apache-crypt@1.2.1 (unix-crypt-td-js@1.0.0)
├── bcryptjs@2.4.3
└── prompt@1.0.0 (revalidator@0.1.8, colors@1.1.2, pkginfo@0.4.0, read@1.0.7, winston@2.1.1, utile@0.3.0)



root@wazuh01:/var/ossec/api/configuration/auth# sudo node htpasswd -c user wazuh
module.js:471
    throw err;
    ^

Error: Cannot find module '/var/ossec/api/configuration/auth/htpasswd'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3


Can you help me, please?


Regards

**Comment by jlruizmlg** [comment]
Hi @santi10 let me help here.

The folder ```/var/ossec/api/configuration/auth/``` should contains two files:

- ```user``` --> This file contains the user and password to work with the API
- ```htpasswd``` --> a symbolic link to ```/var/ossec/api/node_modules/htpasswd/bin/htpasswd```


```
[root@wazuh-manager auth]# ls -la
total 12
drwxr-x--- 2 root root 4096 Aug 10 16:50 .
drwxr-x--- 4 root root 4096 Aug 10 16:50 ..
lrwxrwxrwx 1 root root   49 Aug 10 16:50 htpasswd -> /var/ossec/api/node_modules/htpasswd/bin/htpasswd
-rwxr-x--- 1 root root   42 Jul 25 10:16 user
[root@wazuh-manager auth]#
```

Looking your error seems like for any reason you lost the symbolic link to ```/var/ossec/api/node_modules/htpasswd/bin/htpasswd```

Please verify if the symbolic link exists and if doesn't exist you should create again with:

```ln -sf /var/ossec/api/node_modules/htpasswd/bin/htpasswd /var/ossec/api/configuration/auth/htpasswd```

**Comment by santi10** [comment]
Yes!!!! great. 

Thanks in advance to all for help me!!!!!
