### ISSUE TITLE
Different and opposite errors trying to add a group

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh-api#181]
I tried to add a group with `( )` in his name:
`curl -u foo:bar -k -X PUT "http://127.0.0.1:55000/agents/groups/pciserve()r?pretty" 
{
   "error": 601,
   "message": "Param not valid. Valid characters: a-z, A-Z, 0-9, ., _, -.  Field: group_id"
}`

The API said that `( )` are not valid characters, and the message says that `-` is a valid character.
I tried to add the group with `-` instead of `( )`:

` curl -u foo:bar -k -X PUT "http://127.0.0.1:55000/agents/groups/pciserve-r?pretty"
{
   "error": 1722,
   "message": "Incorrect format for group_id. Characters supported  a-z, A-Z, 0-9, -.=!() Max length is 255."
}`
Now the API message says that `-` is not a supported character, but instead `( )` are supported.

**Comment by mgmacias95** [comment]
Hello @Skeptor,

The regexes used for input validation are now the same in both the API and framework. This has been fixed in https://github.com/wazuh/wazuh/pull/1586.

Best regards,
Marta
