### ISSUE TITLE
Error consulting the active response config of an agent

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh-api#187]
**Version**
Wazuh 3.7

When I try to view an agent's active response configuration I get this error:

![image](https://user-images.githubusercontent.com/9034923/46542903-e28cff00-c8bf-11e8-8356-da15f30b1618.png)

The agent has an active response block in his ossec.conf.

I write the error in the api debugger and it returns:
`{"message": "Wazuh-Python Internal Error: 'JSON input' must have the 'function' key", "error": 1000}`

**Comment by JuanjiJG** [comment]
Hello @Skeptor,

This bug is going to be fixed on the Wazuh app. Here's the issue: https://github.com/wazuh/wazuh-kibana-app/issues/951

Thanks a lot for reporting this!

Regards,
Juanjo
