### ISSUE TITLE
Error with last scan time in syscheck

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh-api#206]
End time from last scan of syscheck is wrong. End time should shows ND if a new scan has started instead the time of last finished scan.
```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/syscheck/000/last_scan?pretty"
{
   "error": 0,
   "data": {
      "start": "2018-09-18 00:27:07",
      "end": "2018-09-18 00:15:19"
   }
}
```

**Comment by davidjiglesias** [comment]
Hello team,

This is already fixed for wazuh new API: https://github.com/wazuh/wazuh/blob/cf33f6cd6c330c278b6540544d0b50c79adb4100/framework/wazuh/syscheck.py#L132
