### ISSUE TITLE
Incorrect cluster/status response

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-api#212]
Hi team, 

I just realized that the `cluster/status` endpoint doesn't response with actual data. Having my cluster enabled and running, if I modify the `<enabled>` value in the `ossec.conf` file, I'm getting the following response *without* restarting the cluster:

```
curl -u foo:bar http://localhost:55000/cluster/status?pretty
{
   "error": 0,
   "data": {
      "running": "yes",
      "enabled": "no"
   }
}

```

Which is not correct in my opinion because the cluster is still running and enabled, so I think the API should return the actual cluster status.

Thanks

**Comment by crd1985** [comment]
I think we can close this issue since you can know the actual status of clusterd after this development https://github.com/wazuh/wazuh/pull/2936
