### ISSUE TITLE
Missing call to know last registered agent

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#221]
Hi team,

As the title says, we have no way to know the last agent unless we fetch agents with limit and sorting parameters.

```js
GET /agents
{
   limit: 1,
   sort: '-dateAdd'
}
```

That's my way to fetch the last registered agent, in my opinion, that's not the best way. 

Regards

**Comment by davidjiglesias** [comment]
Hello team, 

Since 3.10, this feature is provided by new [endpoint](https://documentation.wazuh.com/3.10/user-manual/api/reference.html#summary) `GET /summary/agents`. 

Best regards,
