### ISSUE TITLE
Error in the Docker update: logger

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-api#225]
Hello team,

When we have updated the manager of Wazuh via Docker, when checking the state of the API has shown us the following error: 

```
WazuhAPI 2018-10-26 15:32:07 : Internal Error: uncaughtException
WazuhAPI 2018-10-26 15:32:07 : TypeError: Cannot read property 'uid' of undefined
```

By manually changing the UID and GID values in this section, we have managed to get the service started: 

```
// get ossec uid and gid
fs.stat(path_log + '/api', function(err, stats) {
    ossec_uid = stats['uid'];
    ossec_gid = stats['gid'];
});
```
From: https://github.com/wazuh/wazuh-api/blob/master/helpers/logger.js#L25

Regards,

Alfonso

**Comment by jesuslinares** [comment]
This could work:

> ossec_uid = process.getuid()
