### ISSUE TITLE
Upgrade from 3.6.1 to 3.7.0 Api Error - Wazuh-Python Internal Error: 'nodes'

### ISSUE THREAD

**Issue by sc7565** [wazuh/wazuh-api#239]
After upgrade from 3.6.1 to 3.7.0 resulted in below errors

root@wazuh-manager-uscen-a-c001-n001:/# curl -u admin:admin "http://localhost:55000"
{"error":0,"data":{"msg":"Welcome to Wazuh HIDS API","api_version":"v3.7.0","hostname":"wazuh-manager-uscen-a-c001-n001","timestamp":"Thu Nov 15 2018 23:11:32 GMT+0000 (UTC)"}}

root@wazuh-manager-uscen-a-c001-n001:/# curl -u admin:admin "http://localhost:55000/agents"
{"error":1000,"message":"Wazuh-Python Internal Error: 'nodes'"}

Any idea, I tried installing the manager and now agents have lost connection to manager with error messages as WARNING: (4101): Waiting for server reply (not started).

**Comment by mgmacias95** [comment]
Hello @sc7565,

This is a bug in the API. More precisely, it's a bug that happens when the `<cluster>` configuration in your `ossec.conf` doesn't have a `<nodes>` tag. To fix it, add this to your cluster configuration:
```xml
<nodes>
   <node>localhost</node>
</nodes>
```

Sorry for the inconvenience.

Best regards,
Marta

**Comment by sc7565** [comment]
Thanks @mgmacias95 it worked

**Comment by mgmacias95** [comment]
Hi @sc7565,

I'm glad that hotfix worked for you. This bug has been fixed in https://github.com/wazuh/wazuh/pull/1936/.

Best regards,
Marta
