### ISSUE TITLE
Improve GET /agents/name/:agent_name

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-api#242]
Hi team,

It would be great if we could improve the GET agents by name call.

One of the use cases of this call is to check if an agent exists. So I got the idea that it would be very helpful if we could add some flexibility to this or create a different call, that allows us to match by string and retrieve several matches in case they have, for example:

1. **Using wildcards:**
```
GET /agents/name/AgentTest*
```
Would return:
```
{
    error:"0"
    data: { 
    totalItems:2
    items: [ { name:  AgentTest2, ... },{name: AgentTest1_test, ...  }  ] 
    }
}
```
2. **Match by string** (by default or using an option)
```
GET /agents/name/test?str_included=true
```
Would return:
```
{
    error:"0"
    data: { 
    totalItems:2
    items: [ { name: Agtest1, ... },{ name: testAgent3, ... }  ] 
    }
}
```
3. **Using regex**
```
GET /agents/regex_name
{
re:"^test\d$"
}
```
Would return:
```
{
    error:"0"
    data: { 
    totalItems:2
    items: [ { name: test1, ... },{ name: test3, ...}  ] 
    }
}
```

Let me know what you think about it, and hope this suggestion helps us to improve.

Kind regards,
Miguel

*Update:* Maybe point 3 is a bit harder, but it would be possible to achieve points 1 and 2 changing the SQL query from `WHERE name= :name` to `WHERE name LIKE %name%` in this section of code https://github.com/wazuh/wazuh/blob/master/framework/wazuh/agent.py#L987

**Comment by mgmacias95** [comment]
Hello @migruiz4,

You can filter by queries in the `GET/agents` API call. This way, you could filter by agents whose name contains a specified string (`agent-` in the example):
```javascript
# curl -u foo:bar "localhost:55000/agents?pretty&q=name~agent-"
{
   "error": 0,
   "data": {
      "items": [
         {
            "os": {
               "arch": "x86_64",
               "codename": "Bionic Beaver",
               "major": "18",
               "minor": "04",
               "name": "Ubuntu",
               "platform": "ubuntu",
               "uname": "Linux |agent-1 |4.15.0-43-generic |#46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 |x86_64",
               "version": "18.04.1 LTS"
            },
            "registerIP": "172.17.0.201",
            "lastKeepAlive": "2019-02-15 10:36:09",
            "version": "Wazuh v3.8.2",
            "manager": "master",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00",
            "node_name": "master",
            "mergedSum": "f8d49771911ed9d5c45b03a40babd065",
            "ip": "172.17.0.201",
            "dateAdd": "2019-02-14 15:04:24",
            "group": [
               "default"
            ],
            "id": "001",
            "status": "Active",
            "name": "agent-1"
         },
         {
            "registerIP": "any",
            "node_name": "unknown",
            "ip": "any",
            "dateAdd": "2019-02-15 10:36:13",
            "id": "003",
            "status": "Never connected",
            "name": "agent-2"
         }
      ],
      "totalItems": 2
   }
}
```

I agree that adding support for wildcards and regexes could be a good improvement for the API queries.

I hope this helps,
Marta

**Comment by migruiz4** [comment]
Hi Marta,

This issue was previous to the implementation of the "q" option to query for agents. (Version 3.6.x)

Great work with that! Very useful.

And yes, I'm willing to see more options to retrieve agent information using the API.

Something like regex to perform a case insensitive query would be great.

I'm closing the issue.
Thanks!
