### ISSUE TITLE
Improve GET /agents/:agent_id

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-api#243]
Hi team,

It would be great if we were able to send a json in the request to retrieve information about certain ids, instead of making 1 call for every ID or having to retrieve all the agents (which have a limit of 1000 agents) and then filter, because this is a slow and inefficient solution.

Kind regards,
Miguel

**Comment by jesusgn90** [comment]
Hi @migruiz4 ,

What about `GET /agents?q=id=000,id=001&select=id`? it could be the trick for you!

Regards
