### ISSUE TITLE
Modify group configuration

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#245]
Hi team, due to https://github.com/wazuh/wazuh-kibana-app/issues/1004, the Wazuh API should provide at least one new route to perform the group modification. 

- [x] Define the expected input by the Wazuh API
- [x] Define the method and the path (PUT /agent/groups/:group_id/update ?)
- [x] Define the expected output for both success and fail use cases
- [x] Implementation
- [ ] Mocha test
- [x] Manual test

Regards

**Comment by jesuslinares** [comment]
### Get configuration files

**Get configuration file in a group**
`GET /agents/groups/:group_id/files/:filename`

Examples:
`curl -u foo:bar -X GET "http://localhost:55000/agents/groups/webserver/files/cis_debian_linux_rcl.txt?pretty"`

**Get group configuration (agent.conf)**
`GET /agents/groups/:group_id/configuration`

Note that we have the same result using this request:
`curl -u foo:bar -X GET "http://localhost:55000/agents/groups/webserver/files/agent.conf?pretty"`



### Upload configuration files

**Upload a configuration file to a group**
`POST /agents/groups/:group_id/files/:filename`

Examples:
`curl -u foo:bar -X POST -H 'Content-type: text/xml' -d @agent.conf.xml "http://localhost:55000/agents/groups/webserver/files/agent.conf?pretty"`

Note: Allow only "agent.conf" for the _filename_ param.

**Upload group configuration (agent.conf)**
`POST /agents/groups/:group_id/configuration`

Note that we have the same result using this request:
`curl -u foo:bar -X POST -H 'Content-type: text/xml' -d @agent.conf.xml 
 "http://localhost:55000/agents/groups/webserver/files/agent.conf?pretty"`


**Upload XML files considerations**
- Check if the group exists.
- _filename_ can be only: "agent.conf".
- Verify XML syntax.
- Run Wazuh syntax validator: `/var/ossec/bin/verify-agent-conf -f /var/ossec/tmp/test_agent_conf_<timestamp>`.
- Overwrite file.
