### ISSUE TITLE
New request: Restart agents that belong to a node

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-api#251]
It would be useful to restart agents that belong to a node or a group:
- *POST /agents/restart?node=node01*

**Comment by druizz90** [comment]
Hi team,

API call for restarting agents which belong to a group was added in #43 (it will be included in `3.11` version).

Best regards,

Demetrio.

**Comment by davidjiglesias** [comment]
Already done in https://github.com/wazuh/wazuh/commit/bc9b61f3b341c520365aae3dcd12712e539d7bd6
