### ISSUE TITLE
The symbol "&" is not allowed in xml, in the agents configurations from the APP

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-api#282]
Hi team,

The symbol "&" is not allowed in the configuration of the agents from the APP. If I use a XML validator I can see the following: _The entity name must immediately follow the '&' in the entity reference._

If I use the symbol I see a `XML format error`

![image](https://user-images.githubusercontent.com/23264276/51431952-76e15e80-1c30-11e9-82bd-13145c3581d0.png)

Regards,

Miguel Casares

**Comment by jesuslinares** [comment]
The API must accept only valid XML. We need to change verify-agent tool and the binaries like logcollector: https://github.com/wazuh/wazuh/issues/2447#issuecomment-457635414.

It is temporarily fixed if the file comes from the Wazuh app (https://github.com/wazuh/wazuh/pull/2452).
