### ISSUE TITLE
Debug messages in process output

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-api#284]
Hi, I just noticed that the API service is currently generating debug messages to the process output.

![image](https://user-images.githubusercontent.com/10210567/51468817-240ec080-1d70-11e9-8be7-8bfe235e9f4e.png)

I'm pretty sure this is about `console.log` statements, which are blocking instructions and should be deleted.

Cheers

**Comment by mgmacias95** [comment]
Done here: https://github.com/wazuh/wazuh-api/pull/285
