### ISSUE TITLE
Unable to add agent

### ISSUE THREAD

**Issue by ictinc** [wazuh/wazuh-api#290]
Hi there,
I've recently installed the Wazuh virtual machine. I'm following the description in the manual to add an agent on a server on the same network.
I've tried the method with password and the method with SSL Certificate, both give me error messages:
**With password:**
```
root@monitor:~# /var/ossec/bin/agent-auth -m 192.168.1.109
2019/01/23 00:41:10 agent-auth: INFO: Started (pid: 16201).
INFO: Using password specified on file: /var/ossec/etc/authd.pass
INFO: Connected to 192.168.1.109:1515
INFO: Using agent name as: monitor
INFO: Send request to manager. Waiting for reply.
ERROR: Unable to create key. Either wrong password or connection not accepted by                                                                                                                                                              the manager.
INFO: Connection closed.
```
I did notice that after running `/var/ossec/bin/ossec-authd -P` the 

> Accepting connections on port 1515. Random password chosen for agent authentication: abdc1234
message was not displayed, instead I was just given a new prompt.
Checking with netstat however revealed that ossec-authd was in fact listening on port 1515
`tcp        0      0 0.0.0.0:1515            0.0.0.0:*               LISTEN      6552/ossec-authd`

**With SSL Certificate:**
```
root@monitor:/root# /var/ossec/bin/agent-auth -m 192.168.1.109 -v /var/ossec/etc/rootCA.pem
2019/01/23 00:59:43 agent-auth: INFO: Started (pid: 16377).
INFO: Using password specified on file: /var/ossec/etc/authd.pass
INFO: No authentication password provided.
2019/01/23 00:59:43 agent-auth: ERROR: Problem with certificate at depth 0
2019/01/23 00:59:43 agent-auth: ERROR: issuer =  /C=US/ST=California/CN=Wazuh
2019/01/23 00:59:43 agent-auth: ERROR: subject =  /C=US/ST=California/CN=Wazuh
2019/01/23 00:59:43 agent-auth: ERROR: 18:self signed certificate
139815817720000:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1230:
2019/01/23 00:59:43 agent-auth: ERROR: SSL error (-1). Exiting.
```
Is there something I'm missing here? If I need to add logfiles please specify which.

**Comment by ictinc** [comment]
Fortunately this issue can be solved. A reboot of both servers seems to have fixed the issue and agents can now register.

**Comment by AmelRami** [comment]
Hi, if this problem occurs because of the Wazuh Manager, or you see something like that in your ossec.log file
`ERROR: unable to add agent (from Manager)`
you can run these commands to restart the Wazuh Manager

```shell
systemctl restart wazuh-manager
systemctl restart wazuh-indexer
systemctl restart filebeat.service
systemctl restart wazuh-dashboard
```
