### ISSUE TITLE
Weird output when running rootcheck/syscheck scans on disconnected agents

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#291]
Hi team,

#### Currently

If we try to run a `rootcheck` scan or a `syscheck` scan on a disconnected agent, the API output is not clear.

```js
PUT /rootcheck/001

{
  "error": 1602,
  "message": "Impossible to run syscheck/run due to agent is not active: 001 - Disconnected"
}
...
PUT /syscheck/001

{
  "error": 1602,
  "message": "Impossible to run syscheck/run due to agent is not active: 001 - Disconnected"
}
```
1. `"error": 1602` is being thrown regardless of the API call, we must use different error code.
2. `"Impossible to run syscheck/run due to agent is not active: 001 - Disconnected"` this is wrong because we say `syscheck/run`, this is a typo, it may be `syscheck/rootcheck`. In any case, we should check if it's `syscheck` or `rootcheck`.

#### Expected output

```js
PUT /rootcheck/001

{
  "error": 1111,
  "message": "Impossible to run policy monitoring scan due to agent is not active: 001 - Disconnected"
}
...
PUT /syscheck/001

{
  "error": 2222,
  "message": "Impossible to run FIM scan due to agent is not active: 001 - Disconnected"
}
```

Where 1111 must be a code and 2222 another code, what I meant is that they should be different. When I say `FIM scan` we can use `syscheck`, it's just an idea. When I say `policy monitoring scan` we can use `rootcheck`, it's just an idea.

Regards!

**Comment by mgmacias95** [comment]
Hello @jesusgn90,

The code used to run FIM and policy monitoring scans is the same. [This is the section of the code where the exception you're mentioning is raised](https://github.com/wazuh/wazuh/blob/317e61e1bf5a39988e8c58517bce2e52b6b121d8/framework/wazuh/ossec_queue.py#L118). Two options come to my mind:
* Join the two API calls into a single one.
* Add a new queue message for policy monitoring, separated from the FIM one.

Best regards,
Marta

**Comment by jesusgn90** [comment]
I think this has been fixed [here](https://github.com/wazuh/wazuh/pull/2439)

**Comment by mgmacias95** [comment]
I'll close the issue then. Thanks!
