### ISSUE TITLE
REST for long analisys

### ISSUE THREAD

**Issue by kristianpaul** [wazuh/wazuh-API#3]
Should this API support OSSEC log collection by REST calls? (syslog still not very microservice friendly)

**Comment by jesuslinares** [comment]
Hi kristianpaul,

I'm not sure if I see what you mean. Could you give me an example?.

Thanks.

**Comment by jesuslinares** [comment]
Hi kristianpaul,

if what you mean is if the API will be able to receive logs, the answer is no. The goal is to manage OSSEC, not replace its work (_logcollector_).

Thanks for your interest.
Regards.
