### ISSUE TITLE
API /syscheck/:agentid/last_scan gives wrong data after PUT to /syscheck/:agentid

### ISSUE THREAD

**Issue by pm17788** [wazuh/wazuh-api#306]
When a new SysCheck is kicked off by way of `PUT /syscheck/:agentid`, a call to `/syscheck/:agentid/last_scan` returns the *new* scan's start date, and the *previous* scan's end date, which is eminently confusing.
Example:
```json
{
  "error": 0,
  "data": {
    "start": "2019-02-08 13:44:47",
    "end": "2019-02-08 10:28:31"
  }
}
```

The start is _after_ the end, which is problematic. Perhaps on `PUT /syscheck/:agentid`, and upon receiving a confirmation of the check start, the end should be reset to `ND`?

**Comment by mgmacias95** [comment]
Hello @pm17788,

You're right, if the `start` date is higher than the `end` date we should return the `end` as `ND`. 

Thank you so much for reporting this bug 😄!

Best regards,
Marta

**Comment by mgmacias95** [comment]
Duplicated: https://github.com/wazuh/wazuh-api/issues/206

**Comment by pm17788** [comment]
Since this is duplicated in #206, closing.
