### ISSUE TITLE
Change configuration_assessment request parameter name

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-api#310]
Hi team,

We would like, if possible, that in the call `GET /configuration_assessment/:agent_id/checks/:id` the name of the last parameter was `:policy_id` instead of only `:id`.

Regards.

**Comment by crd1985** [comment]
Hi @juankaromo,
we have already changed that in our branch. It will be merged as soon as it is tested.

If you don't have any inconvenience, I'll close this issue.

Regards,
