### ISSUE TITLE
Service doesn't start on latest from master.

### ISSUE THREAD

**Issue by sc-chad** [wazuh/wazuh-api#32]
Thought I would try out 3.0.
Running in AWS Amazon Linux.

Just pulled master 3.0? Ran ./install_api.

```### Wazuh API ###

Installing Wazuh API 3.0.0-beta9 from current directory [DEV MODE].

Installing API ['/var/ossec/api'].

Installing NodeJS modules.

Installing service.
----------------------------------------------------------------
Installing for SysVinit
init script installed in /etc/init.d/wazuh-api
We could not enable it. Please enable the service manually.
----------------------------------------------------------------

API URL: http://host_ip:55000/
user: 'foo'
password: 'bar'
Configuration: /var/ossec/api/configuration
Test: curl -u foo:bar -k http://127.0.0.1:55000?pretty
Note: You can configure the API executing /var/ossec/api/scripts/configure_api.sh

### [API installed successfully] ###```

```/etc/init.d/wazuh-api status
WAZUH-API is stopped.

Last 20 log entries:

Full log: /var/ossec/logs/api.log```

But no process or logs.  I am running the latest from the Wazuh repo as well.

**Comment by mgmacias95** [comment]
Hi @sc-chad,

The master branch of https://github.com/wazuh/wazuh/ is at version 3.1 and the master branch of the API is at version 3.0. 

Please, change wazuh branch to 3.0 and reinstall again:
```shellsession
[user@wazuh]$ git checkout 3.0
[user@wazuh]$ sudo ./install.sh 
[user@wazuh]$ cd path/to/wazuh-api/repo
[user@wazuh]$ sudo ./install_api.sh
```

That should fix your error.

Best regards,
Marta

**Comment by sc-chad** [comment]
Same issue ;(

**Comment by mgmacias95** [comment]
Hi @sc-chad,

Which nodeJS version are you using? The API needs nodeJS 6.

Best regards,
Marta

**Comment by sc-chad** [comment]
```node -v
v6.2.0```

**Comment by sc-chad** [comment]
running ```
node app.js
``` 

gives:

```
node app.js
/var/ossec/api/configuration/config.js:77
config.secureOptions = crypto.constants.SSL_OP_NO_SSLv3 |
                                       ^

TypeError: Cannot read property 'SSL_OP_NO_SSLv3' of undefined
```

**Comment by sc-chad** [comment]
removing those config.secureOptions seems to fix the issue.

**Comment by mgmacias95** [comment]
Hi @sc-chad,

The library `crypto` should be built-in in NodeJS. It is used at `config.js` file: 

https://github.com/wazuh/wazuh-api/blob/78ba27ef27f297aab44bab3a0c1f0048c2be60b5/configuration/config.js#L76-L80

We though that library came preinstalled at NodeJS 6. Please, can you check if you have it installed on your NodeJS? 

Best regards,
Marta

**Comment by mgmacias95** [comment]
Please, also note that if you delete that lines from `config.js` file you won't be able to configure HTTPS on the API. We will review this bug.

Thank you so much for reporting!
Marta

**Comment by sc-chad** [comment]
Doesn't look like it comes preinstalled.  I also ran `npm install crypto` but that didn't seem to fix it either.  No problem on the no SSL portion, appreciate the help!
