### ISSUE TITLE
Script does not handle spaces in password

### ISSUE THREAD

**Issue by keaneokelley** [wazuh/wazuh-api#33]
https://github.com/wazuh/wazuh-api/blob/78ba27ef27f297aab44bab3a0c1f0048c2be60b5/examples/api-register-agent.sh#L32
and
https://github.com/wazuh/wazuh-api/blob/78ba27ef27f297aab44bab3a0c1f0048c2be60b5/examples/api-register-agent.sh#L48

If the API password for basic authentication contains spaces, the variable substitution does not correctly take place during both curl commands, causing the script to fail with no error message (very unhelpful). It likely won't handle other special characters as well.

**Comment by albertomn86** [comment]
Hi @keaneokelley,

Indeed, in both curl commands the variable substitution is not working properly when a space character is included.

You can perform a quick fix by adding quotation marks to the variable:

`GET_ID=$(curl -s -u $USER:"$PASSWORD" -k -X POST -d 'name='$AGENT_NAME $PROTOCOL://$API_IP:$API_PORT/agents)`

However, I will update the script with this change.

Thank you for reporting this issue.

Best regards.

**Comment by albertomn86** [comment]
Fixed!
https://github.com/wazuh/wazuh-api/commit/d2c5329fcceaa8e99551e28a86eb5cfd8f211cc6
