### ISSUE TITLE
Save Wazuh API entry - 3005,Internal error

### ISSUE THREAD

**Issue by hwb2017** [wazuh/wazuh-api#331]
Elastic Stack version v6.6.1
Wazuh manager/agent/API/APP version v3.8.2

i can access wazuh api with my credential through CURL
```
curl -u admin:xxxxxx http://10.200.112.91:55000?pretty
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.8.2",
      "hostname": "xxxxxx",
      "timestamp": "Mon Feb 25 2019 20:03:29 GMT+0800 (CST)"
   }
}
```
but when i save wazuh api entry in wazuh app,it returns 3005 - Internal error

kibana logs:

```
{"type":"response","@timestamp":"2019-02-25T11:50:37Z","tags":[],"pid":15352,"method":"post","statusCode":500,"req":{"url":"/api/check-api","method":"post","headers":{"host":"10.200.112.62:5601","connection":"keep-alive","content-length":"252","accept":"application/json, text/plain, */*","origin":"http://10.200.112.62:5601","kbn-version":"6.6.1","user-agent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","content-type":"application/json","referer":"http://10.200.112.62:5601/app/wazuh","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9"},"remoteAddress":"10.86.4.4","userAgent":"10.86.4.4","referer":"http://10.200.112.62:5601/app/wazuh"},"res":{"statusCode":500,"responseTime":13,"contentLength":9},"message":"POST /api/check-api 500 13ms - 9.0B"}
```

wazuh app logs:
```
{"date":"2019-02-25T11:42:59.171Z","level":"error","location":"POST /api/check-api","message":"Internal error"}
```
![cfefdc69ff43431bac3d1286f0f38faa](https://user-images.githubusercontent.com/27839771/53335952-d15c9180-3937-11e9-8a49-3292b7867637.png)

**Comment by jesusgn90** [comment]
Let's try to put the Wazuh API in `debug` mode, so we can look for detailed messages in the `api.log` file.

Replace the log level in file `/var/ossec/api/configuration/config.js`:


Replace "info" with "debug"
```
sed 's:config.logs = "info":config.logs = "debug":g' /var/ossec/api/configuration/config.js
```

Restart Wazuh API
```
systemctl restart wazuh-api
```

Now open a new CLI and `tail -f` the Wazuh API log:

```
tail -f /var/ossec/logs/api.log
// Press ENTER 4-5 times to clear the output
```

In a different CLI, execute these two `curl` commands:

```
curl -u foo:bar wazuh_api:55000/agents/000
curl -u foo:bar wazuh_api:55000/cluster/status
```

Now the `api.log` should be a bit more detailed.

Regards

**Comment by hwb2017** [comment]
Hi @jesusgn90 
Thanks for your guide.I switched `wazuh-api` to debug mode and found the output as shown below:
```
WazuhAPI 2019-02-26 08:28:22 foo: ::ffff:10.200.112.62 GET /agents/:agent_id
WazuhAPI 2019-02-26 08:28:22 foo: CMD - Command: python args:/usr/local/xxxxx/wazuh/api/models/wazuh-api.py stdin:{"function":"/agents/:agent_id","arguments":{"agent_id":"000","wait_for_complete":false},"ossec_path":"/usr/local/xxxxx/wazuh"}
WazuhAPI 2019-02-26 08:28:22 foo: CMD - Exit code: 0
WazuhAPI 2019-02-26 08:28:22 foo: CMD - STDOUT:
---
{"message": "Wazuh-Python Internal Error: No module named wazuh", "error": 1000}
---
WazuhAPI 2019-02-26 08:28:22 foo: CMD - STDOUT: 81 bytes
WazuhAPI 2019-02-26 08:28:22 foo: Wazuh-Python Internal Error: No module named wazuh
WazuhAPI 2019-02-26 08:28:22 foo: [::ffff:10.200.112.62] GET /agents/000 - 200 - error: '1000'.
```
The output of  command `curl -u foo:bar wazuh_api:55000/cluster/status`  looks quite similarily.

Then i dug into the detail of `MY_WAZUH_PATH/api/models/wazuh-api.py`, i found something interesting:
```
# wazup-api.py line 17 to line 24
try:
    new_path = '/var/ossec'
    if not os_path.exists(new_path):
        current_path = path[0].split('/')
        new_path = "/{0}/{1}".format(current_path[1], current_path[2])
    new_framework_path = "{}/framework".format(new_path)
    path.append(new_framework_path)
    from wazuh import Wazuh
```
I set breakpoint and got the value of my variable `new_framework_path`, it's `/usr/local/framwork`.
So far, it's no wonder that module wazuh is not found, as the preceding directory is not exists, the  correct directory in my situation should be `/usr/lcoal/xxxxx/wazuh/framwork`.
It assumed my customed path looks like `/xxx/xxx`, but my path is `/usr/local/xxxxx/wazuh`.
Then i researched the way to acquire customed path as the wazuh-api installation script `install_api.sh` does, and tuned the source code.
```
try:
    new_path = '/var/ossec'
    if not os_path.exists(new_path):
        #current_path = path[0].split('/')
        #new_path = "/{0}/{1}".format(current_path[1], current_path[2])
        with open("/etc/ossec-init.conf") as ossec_init_conf:
            for conf in ossec_init_conf:
                if "DIRECTORY" in conf:
                   new_path = conf.split("=")[1].replace('"','').rstrip()
    new_framework_path = "{}/framework".format(new_path)
    path.append(new_framework_path)
    from wazuh import Wazuh
```
Now it works. Module wazuh can be recognized.
But new error comming:
```
WazuhAPI 2019-02-26 11:04:14 foo: ::ffff:10.200.112.62 GET /agents/:agent_id
WazuhAPI 2019-02-26 11:04:14 foo: CMD - Command: python args:/usr/local/xxxxx/wazuh/api/models/wazuh-api.py stdin:{"function":"/agents/:agent_id","arguments":{"agent_id":"000","wait_for_complete":false},"ossec_path":"/usr/local/xxxxx/wazuh"}
WazuhAPI 2019-02-26 11:04:14 foo: CMD - Exit code: 0
WazuhAPI 2019-02-26 11:04:14 foo: CMD - STDOUT:
---
---
WazuhAPI 2019-02-26 11:04:14 foo: CMD - STDOUT: 0 bytes
WazuhAPI 2019-02-26 11:04:14 foo: CMD - STDOUT NOT JSON
WazuhAPI 2019-02-26 11:04:14 foo: [::ffff:10.200.112.62] GET /agents/000 - 500 - error: '2'.
WazuhAPI 2019-02-26 11:04:14 foo: Response: {"error":2,"message":"Command output not in JSON"} HTTP Status: 500
```

**Comment by jesusgn90** [comment]
So, is it working for you? We should review this use case because it's expected to work without modifying the source code. Is your installation path `/usr/local/xxxx/wazuh/` instead of `/var/ossec`, right? Let us review your last comment, thanks.

Can we review https://github.com/wazuh/wazuh-api/issues/331#issuecomment-467275603 @wazuh/framework ?

Regards

**Comment by hwb2017** [comment]
My installation path is displayed in `/etc/ossec-init.conf`:
```
DIRECTORY="/usr/local/xxxxx/wazuh"
NAME="Wazuh"
VERSION="v3.8.2"
REVISION="3814"
DATE="Tue Feb 19 14:40:21 CST 2019"
TYPE="server"
```
In debuging the `MY_WAZUH_PATH/api/models/wazuh-api.py`, I set the breakpoint just after the first try-catch block where module wazuh is imported, and I got the values below:
```
current_path ===> ['', 'usr', 'local', 'xxxx', 'wazuh', 'api', 'models']
new_path ===> /usr/local
new_framework_path ===> /usr/local/framework
```
And the error `No module named wazuh` arose as the oringinal situation.

**Comment by crd1985** [comment]
Hi @hwb2017 ,
you are totally right. Our code is not correct since we are supposing the user path has always two levels only.
However, this use case should be working perfectly in the next version since we have introduced several improvements regarding Python packages in current roadmap. Now wazuh will be one more package under Python 'site-packages' path, so there is no need to manipulate the Python path.

Said that, we will test your use case to guarantee everything will be ok in next release, just keep your fix until you upgrade.

Thank you very much for reporting this issue!

Regards

**Comment by crd1985** [comment]
Sorry, I didn't see your previous comment. We will review your code snippet and propose a fix for your use case.

Regards

**Comment by crd1985** [comment]
Well the obvious quick fix here is to carry on working with Wazuh is to change the line:
```python
new_path = '/var/ossec'
```
to match your custom path
```python
new_path='/usr/local/xxxxx/wazuh'
```
and wait for the next version that will be released soon. Those lines of code before the import statement will have disappeared then, so it is not worth your time to fix them :)

I hope it helps.

Regards.

**Comment by hwb2017** [comment]
Hi @crd1985 ,
I have fix the problem and experiencing Wazuh APP's multiple features now.

According to your last comment, I'm looking forward to Wazuh's later release.

Best regards.
