### ISSUE TITLE
Error retreiving data from Wazuh DB 

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh-api#333]
Hello Team,

While trying to retrieve data from Wazuh DB using for instance this API call :

`GET /syscollector/agentid/packages `

This error is being raised : `ERROR retreiving data from Wazuh DB` . 

![testtest](https://user-images.githubusercontent.com/16334770/53515333-00a30800-3aca-11e9-83eb-6374c87f8a36.png)

and this is caused when some using special characters that's aren't being currently encoded in this particular case some letters in Portuguese are the reason :

![screenshot from 2019-02-27 18-45-56](https://user-images.githubusercontent.com/16334770/53515122-8d999180-3ac9-11e9-9494-e126f01b8682.png)

**Comment by mgmacias95** [comment]
Hello @elwali10,

Thanks for reporting this issue. It can be fixed using what I commented in https://github.com/wazuh/wazuh/issues/1202#issuecomment-469178999 at API level. It would be great that @wazuh/core deep into the issue and find out why this strange character appeared inside the database.

Best regards,
Marta
