### ISSUE TITLE
"internal" option in documentation repeats 3 times

### ISSUE THREAD

**Issue by JaoChaos** [wazuh/wazuh-api#336]
Hi team, 

in this issue -> https://github.com/wazuh/wazuh-documentation/issues/966 is related that the "internal" option in the GET /agents/:agent_id/config/:component/:configuration section repeats 3 different times.

As the API documentation is generated by itself, you should check this slip.

Best regards,

Juan Anaya Ortiz.

**Comment by mgmacias95** [comment]
Hello @JaoChaos,

This issue will be fixed with the migration to OpenAPI we're doing for Wazuh 4.0. It won't be fixed for 3.x releases.

Best regards,
Marta

**Comment by davidjiglesias** [comment]
Fixed in Wazuh v4.0.0
