### ISSUE TITLE
Agents: Wazuh API returned an error message. Error: There is no database for selected agent.

### ISSUE THREAD

**Issue by sc-chad** [wazuh/wazuh-api#34]
Was working great on 3.0 then I started adding a bunch of agents.  Now getting this in Kibana.

Tried restarting the service and received same error.  Agents should be in the 200-300 range.

Sorry more context:

This is only happening on the Agents tab in the Wazuh Kibana app.

I haven't updated this since I moved to 3.0.  Is there a version I should update to here as well?

**Comment by mgmacias95** [comment]
Hi @sc-chad,

That error is very usual in a fresh install of wazuh. Please, try restarting the Wazuh manager:

```shellshession
# /var/ossec/bin/ossec-control restart
```

If that doesn't work, please check if the API database exists: 

```shellsession
# sqlite3 /var/ossec/var/db/global.db
```

If it exists, remove it and restart the manager again.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello @sc-chad,

I'm closing this issue since it's been opened for too long. Please, feel free to re-open it if you need to.

Best regards,
Marta
