### ISSUE TITLE
agents/agent/agent_name response code

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-api#343]
Hello team,

I've noticed that when you call `/agents/name/agent_name` and the requests fails for some reason (for example, there's no agent with that name), the response is `200`.

Shouldn't it be different? Maybe 404?

Regards.

**Comment by mgmacias95** [comment]
Hello @havidarou,

This issue will be fixed with the migration to OpenAPI we're doing for Wazuh 4.0. It won't be fixed for 3.x releases.

Best regards,
Marta

**Comment by davidjiglesias** [comment]
Done in v4.0.0
