### ISSUE TITLE
Add docu examples of body/queries parameters. 

### ISSUE THREAD

**Issue by JaoChaos** [wazuh/wazuh-api#350]
Hi team:

In a community thread, I've checked that in the documentation is not showed differentiation between the fields that are included in a call in the body, and those that are included in the query.

It would be cool to add a few examples where is shown where to place the different parameters.

Best regards,

Juan Anaya Ortiz.

**Comment by mgmacias95** [comment]
Hello @JaoChaos,

This issue will be fixed with the migration to OpenAPI we're doing for Wazuh 4.0. It won't be fixed for 3.x releases.

Best regards,
Marta
