### ISSUE TITLE
Can't connect Wazuh APP to API : Internal error

### ISSUE THREAD

**Issue by MethylHaine** [wazuh/wazuh-api#356]
Hi all,

After upgrading Manager, API and Wazuh APP from 3.2.2 to 3.8.2 we encounter an issue when connecting the Wazuh APP to the API, with the following Message : 

![image](https://user-images.githubusercontent.com/22054392/54908437-34febe00-4ee8-11e9-8381-cf3c466177dd.png)

The info provided in order to connect the Wazuh APP to the API is correct.
However we do get these errors :

```
curl -u foo:bar http://localhost:55000/agents/000?pretty
{
   "error": 1000,
   "message": "Internal error"
}
```

In wazuhapp.log, everything is fine except :

![image](https://user-images.githubusercontent.com/22054392/54908730-da199680-4ee8-11e9-8f14-981389fcb017.png)

Versions :

- Manager : 3.8.2
- API : 3.8.2
- Wazuh APP : 3.8.2
- ELK : 6.6.1

Any idea where the issue could be ?

**Comment by druizz90** [comment]
Hi @MethylHaine, could you pass me the output of `systemctl status wazu-api` and the content of `config.js` file? It is possible that some values in API configuration were missed with your upgrade.

**Comment by MethylHaine** [comment]
Hi @druizz90, thanks for your answer.
The service is running fine :
![image](https://user-images.githubusercontent.com/22054392/54926639-03e6b380-4f11-11e9-92b9-a60802145227.png)

See config.js attached.
[config.zip](https://github.com/wazuh/wazuh-api/files/3003687/config.zip)

I've checked configuration of the manager and had some warning with deprecated cluster options, corrected but the issue persists.

May have missed something in the config still.

**Comment by druizz90** [comment]
Hi @MethylHaine, could you replace in`config.js` the line `config.logs = "info";` by `config.logs = "error";` and restart API with `systemctl restart wazuh-api`? See `WAZUH_PATH/logs/api.log` file after doing that.

**Comment by MethylHaine** [comment]
Restarted just fine
Output of api.log after another attempt of registering API in Wazuh APP:
```
WazuhAPI 2019-03-25 16:39:30 : Listening on: http://0.0.0.0:55000
WazuhAPI 2019-03-25 16:41:50 undefined: [XXX.XX.XX.XX] GET /version? - 200 - error: '0'.
WazuhAPI 2019-03-25 16:41:50 undefined: Wazuh-Python Internal Error: No module named wazuh
WazuhAPI 2019-03-25 16:41:50 undefined: [XXX.XX.XX.XX] GET /agents/000? - 200 - error: '1000'.
```

**Comment by mgmacias95** [comment]
Hello @MethylHaine,

I think your error is raised in this code lines:
https://github.com/wazuh/wazuh-api/blob/7cd5ef15f668f52324c7f8ebf8677fb1e1106aaf/models/wazuh-api.py#L18-L25

That code is going to be deprecated in our next release (Wazuh 3.9) so I'd waste no time trying to find out what's happening. I'd change the `new_path` variable declaration to `/OPT/ossec`.

Best regards,
Marta

**Comment by MethylHaine** [comment]
Hi @mgmacias95 ,

This indeed fixes the issue !
After upgrading the templates and restarting ELK everything is running fine.

Thanks a lot for your answer, this thread can be closed.

Best regards,
