### ISSUE TITLE
Get XML from non-local rules/decoders files

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-api#369]
Hi team,

Since local rule/decoder files can be edited from within the Wazuh app, it would be nice if a user could also view non-local rule/decoder files in XML, since the user usually copies existing rules/decoders before creating/editing a local one. 

Only the reading function would be necessary, no update/delete is necessary.

Regards.

**Comment by druizz90** [comment]
Hi,

I think one solution for this could be to allow getting files from `ruleset/rules` and `ruleset/decoders`  with `manager/files` endpoint. This endpoint `/manager/files?path=XXXX` only allows getting files from `etc/rules`, `etc/decoders` and `/etc/lists` directories (and `ossec.conf` file).

Other solution may be to add a new parameter in a rule endpoint for getting the content of one rule file.

Thoughts?
