### ISSUE TITLE
Improvements and fixes in api-register-agent.ps1 script

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-api#392]
Hi team,

We have reported several problems with the script api-register-agent.ps1, one of them is that if it runs twice in a row, creates duplicate lines due to the previous execution, it is true that the script is intended to be executed only once but we should add some method of verification to avoid this.
The other bugs are mostly related to the version of Powershell that executes the script (problems when converting from a JSON to a Powershell object).

This is one of the outputs of these errors:

ConvertFrom-Json : Invalid JSON primitive: System.Net.WebException.
At C:\scripts\api-register-agent.ps1:89 char:70
+ ... -method "GET" -resource "/agents/$($agent_id)/key" | ConvertFrom-Json
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

Best regards,
Adri

**Comment by davidjiglesias** [comment]
This script will be deprecated with the release of 4.0.

Regards,

David J. Iglesias
