### ISSUE TITLE
Wazuh-api service installation fails in CentOS 6 docker container

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-api#402]
Hello team

  We have noticed that if we try to install wazuh-api in CentOS 6 docker container, the installation doesn't work completely due to the installation service script. 

 We started the CentOS 6 container by: 
```
docker run --rm -ti centos:6 bash
```
Then we followed the installation guide. After installing the wazuh-api with this: 
```
yum install wazuh-api
```
we noticed that the daemon was not launched. We debugged the service installation script: https://github.com/wazuh/wazuh-api/blob/master/scripts/install_daemon.sh and looks like if the line:

https://github.com/wazuh/wazuh-api/blob/master/scripts/install_daemon.sh#L79

doesn't work as expected. 

Best regards, 
Alberto R

**Comment by druizz90** [comment]
Hi team,

I tried to install our API in Docker images (`CentOS 7` and `Ubuntu 18.04`) and I have the same problem. These images have not a service system such as `systemd`.

One solution could be to add this line in the last `else` block of `install_daemon.sh` script (it only show a message for executing this line):

```bash
${BIN_DIR} ${APP_PATH} > /dev/null 2>&1 < /dev/null &
```

Best regards,

Demetrio.
