### ISSUE TITLE
Wazuh API kept loading

### ISSUE THREAD

**Issue by kenyjeanreyes** [wazuh/wazuh-api#415]
I can access Kibana properly, and as I've checked, everything's up and running. But when I loaded  the wazuh api, it's been running and loading for minutes now. I thought my PC was just slow, but everything else is working just fine.

I was thinking that maybe it had something to do **when I changed my IP address into static.**

Is there any other way where I can configure my Wazuh API settings without having to access the website?

**Comment by davidjiglesias** [comment]
Hi @kenyjeanreyes, you can configure Wazuh api in `/var/ossec/api/configuration/config.js`

**Comment by kenyjeanreyes** [comment]
Thank you very much!
