### ISSUE TITLE
Wazuh error when tying to start

### ISSUE THREAD

**Issue by tmaster8** [wazuh/wazuh-api#421]
![Wazuh error](https://user-images.githubusercontent.com/35183767/61718440-fdd2d900-ad30-11e9-928a-564b0cf5e017.PNG)
 
and I know this is the error handling for app.js 
![wazuh app](https://user-images.githubusercontent.com/35183767/61719988-f3660e80-ad33-11e9-9d01-57a9be889f30.PNG)

**Comment by AdriiiPRodri** [comment]
Hi @tmaster8,

Thank you very much for your time, let's investigate this problem. Could you please tell me which operating system and the version number of it?

Did this error happen following the Wazuh API installation guide? [Wazuh installation guide](https://documentation.wazuh.com/3.x/installation-guide/installing-wazuh-server/wazuh_server_linux.html). Inside the previous link we must choose our operating system and follow the specified steps.

In any case I wait for your answer so I can help you with this problem.

Best regards,
Adri

**Comment by tmaster8** [comment]
Amazon AMI Linux 2

**Comment by AdriiiPRodri** [comment]
I see, let's see why this can happen in your system, can you please run these commands and show me the output?

```bash node --version```
```bash npm -g ls --depth=0```

When you installed node, did you do it as **root** user?

**Comment by tmaster8** [comment]
@AdriiiPRodri I assume it has to do with http-auth? 
![node](https://user-images.githubusercontent.com/35183767/61798651-ac415180-adf7-11e9-963f-cc58ea3cd1a4.PNG)
![http](https://user-images.githubusercontent.com/35183767/61798681-b8c5aa00-adf7-11e9-8476-c8dbd0aef0cf.PNG)

**Comment by AdriiiPRodri** [comment]
Yes, it has to do with that module. I see that the current version of node installed on your system is node 6.17.1. I recommend you install version 8.x of node.
In any case we are going to try to solve it, let's execute the following command and see what it returns to us:
```bash
ls -lth /var/ossec/api/node_modules/ 
```

**Comment by tmaster8** [comment]
@AdriiiPRodri 
![node](https://user-images.githubusercontent.com/35183767/61800271-adc04900-adfa-11e9-9245-fcf21b6e3634.PNG)
![node 2](https://user-images.githubusercontent.com/35183767/61800274-af8a0c80-adfa-11e9-8979-94fdac111076.PNG)
![node 3](https://user-images.githubusercontent.com/35183767/61800276-b0bb3980-adfa-11e9-9a50-ba2ab613d385.PNG)

**Comment by AdriiiPRodri** [comment]
Ok @tmaster8, the module seems to be correct in your installation, however let's try the following:

1º Let's remove the module from the API:
```bash
rm -r /var/ossec/api/node_modules/http-auth/
```

2º Now we will reinstall the module:
```bash
npm install --prefix /var/ossec/api http-auth
```

3º Restart the API and check if the error persists

**Comment by tmaster8** [comment]
@AdriiiPRodri Problem still persists

**Comment by tmaster8** [comment]
@AdriiiPRodri 
![npm](https://user-images.githubusercontent.com/35183767/61803747-bd429080-ae00-11e9-9295-49e486fcb5b2.PNG)

**Comment by AdriiiPRodri** [comment]
Let's go to the path /var/ossec/api:
```bash
cd /var/ossec/api
```

And run the following to be able to check that its output is correct:
```bash
npm install
```

**Comment by tmaster8** [comment]
@AdriiiPRodri 
![npm](https://user-images.githubusercontent.com/35183767/61804314-b5cfb700-ae01-11e9-917f-59e3a7c06b5a.PNG)

**Comment by AdriiiPRodri** [comment]
I think this may be happening in another part of the code. Let's do one:

```bash
ls -lth /var/ossec/api/helpers
```

And we'll see if everything is correct in this folder.

**Comment by tmaster8** [comment]
@AdriiiPRodri 
![image](https://user-images.githubusercontent.com/35183767/61805444-cb45e080-ae03-11e9-80fa-3fdce560d805.PNG)

**Comment by AdriiiPRodri** [comment]
All right in this folder, let's see the contents of the http-auth folder:

```bash
ls -lth /var/ossec/api/node_modules/http-auth
```

And then:
```bash
ls -lth /var/ossec/api/node_modules/http-auth/src
```

**Comment by tmaster8** [comment]
@AdriiiPRodri 
![auth](https://user-images.githubusercontent.com/35183767/61805756-5fb04300-ae04-11e9-87d4-bde6ed9eb60d.PNG)

**Comment by AdriiiPRodri** [comment]
Ok @tmaster8, I see that the permissions on these files are not correct. Let's do the following, as a **root** user we will execute the following commands:

```bash
rm -rf /var/ossec/api/node_modules/*
```

After this we are going to do the following:
```bash
cd /var/ossec/api
```

The next thing is to reinstall all dependencies:
```bash
npm install
```

Finally, we restart the API

**Comment by tmaster8** [comment]
@AdriiiPRodri new 
![wazuh](https://user-images.githubusercontent.com/35183767/61806616-00533280-ae06-11e9-8406-3e9c8a423683.PNG)
error code

**Comment by AdriiiPRodri** [comment]
This is unusual, we are going to confirm that everything has gone correctly. Let's list the elements of **/var/ossec/api/node_modules**:

```bash
ls -lth /var/ossec/api/node_modules
```

**Comment by tmaster8** [comment]
@AdriiiPRodri 
![image](https://user-images.githubusercontent.com/35183767/61806981-b1f26380-ae06-11e9-9e33-c9ecf97f76ff.png)
![image](https://user-images.githubusercontent.com/35183767/61807033-c6cef700-ae06-11e9-8123-4acff7772b90.png)
![image](https://user-images.githubusercontent.com/35183767/61807070-d3534f80-ae06-11e9-9b1f-aeda749f4d88.png)
![image](https://user-images.githubusercontent.com/35183767/61807091-dd754e00-ae06-11e9-9f5e-28414851d7d1.png)
![image](https://user-images.githubusercontent.com/35183767/61807126-e9f9a680-ae06-11e9-89e6-038d52cfa91c.png)

**Comment by tmaster8** [comment]
@AdriiiPRodri 
Nvm I figured it out! Thanks for the help!

**Comment by AdriiiPRodri** [comment]
Great @tmaster8, I'm so glad I helped you. In order to help other users, you could tell me what the error was, have you installed nvm, have you changed the version of node?

**Comment by tmaster8** [comment]
@AdriiiPRodri after following all your steps, I just completely uninstalled and re-installed the wazuh-api via yum
