### ISSUE TITLE
New Request: fully pull a modified file from an agent

### ISSUE THREAD

**Issue by lucanus81** [wazuh/wazuh-api#434]
Hi,

I have been facing the limitation of `<directories report_changes="yes"> ... </directories>` for non-Unix systems. My question is: is there any way -via the API- to see what really changed?
Wouldn't be nice to extend the syscheck API in order to fully return the modified file?

Thanks,
Luca

**Comment by AdriiiPRodri** [comment]
Hi @lucanus81,

Currently it is not possible to see what has actually changed in the file through the API, however, we are considering the possibility of adding this in the near future.

On the other hand, syscheck with the flag report_changes should work in any system compatible with Wazuh, could you please tell me the version you are running of Wazuh, both the agent and the nodes manager as well as the system type of the agent, is Windows or Mac?

Thank you for your time and your report, I wait for your answer, for any doubt do not hesitate to ask. 

Best regards,
Adri

**Comment by lucanus81** [comment]
Hi,
thanks for your quick answer! 
We use the agentless configuration with a CentOS master, and Mac OS X 10.14.15, Ubuntu 18.04.3 LTS, and Windows 2016 server (considering agentless is not supported for Windows, we installed the latest windows agent available: wazuh-agent-3.9.5-1.msi).

This is my master configuration:
`[root@localhost wazuh]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 
[root@localhost wazuh]# curl -u foo:bar http://localhost:55000/manager/info
{"error":0,"data":{"path":"/var/ossec","version":"v3.9.5","compilation_date":"Thu Aug  8 12:27:15 UTC 2019","type":"manager","max_agents":"14000","openssl_support":"yes","ruleset_version":"v3.9.5","tz_offset":"-0400","tz_name":"EDT","name":"localhost.localdomain","cluster":{"enabled":"no","running":"no","name":"wazuh","node_name":"node01","node_type":"master"}}}[root@localhost wazuh]#`

You're right, the `ssh_generic_diff`works fine and we get all the changes reported, however (I am not sure this is an issue with my configuration) even if we know what has changed, the alert we receive doesn't contain the file name that was changed. For example:
`{"timestamp":"2019-08-15T08:22:34.043-0700","rule":{"level":7,"description":"Integrity checksum for agentless device changed.","id":"555","firedtimes":2,"mail":false,"groups":["ossec","syscheck","agentless"],"pci_dss":["11.5","10.6.1"],"gpg13":["4.11"],"gdpr":["II_5.1.f","IV_35.7.d"]},"manager":{"name":"ubuntu"},"id":"1565882554.593828","full_log":"ossec: agentless: Change detected:\n2d1\n< exit\n","decoder":{"name":"ossec"},"location":"agentless","agentless":{"script":"ssh_generic_diff","user":"luca","host":"172.16.204.164"}}`

On the contrary, `ssh_integrity_check_bsd` shows what file was changed/added like in this example (in particular I am referring to the fields "syscheck/path", and "host")
`{"timestamp":"2019-08-16T10:13:39.421-0400","rule":{"level":7,"description":"Integrity checksum changed.","id":"550","firedtimes":2,"mail":false,"groups":["ossec","syscheck"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"]},"manager":{"name":"localhost.localdomain"},"id":"1565964819.108220","full_log":"File '/tmp/luca/sample.txt' checksum changed.\nSize changed from '58' to '35'\nOld md5sum was: '617cc501da874b887240d203611799bd'\nNew md5sum is : '4f173a4ff1dbe1a4525675ec6b0bacda'\n","syscheck":{"path":"/tmp/luca/sample.txt","size_before":"58","size_after":"35","perm_after":"100644","uid_after":"501","gid_after":"0","md5_before":"617cc501da874b887240d203611799bd","md5_after":"4f173a4ff1dbe1a4525675ec6b0bacda","event":"modified"},"decoder":{"name":"syscheck_integrity_changed"},"location":"syscheck","agentless":{"script":"ssh_integrity_check_bsd","user":"luca","host":"172.16.204.236"}}`

Right now we are using a hybrid solution where we use `ssh_integrity_check_bsd` for monitoring changes, while we use Ansible to fully retrieve the file that has changed. 
Unfortunately we cannot restrict ourself to text-files, our customer can decide to monitor anything, like a jar file, a certificate, and so on).

The REST API already allows to get the result of the last scancheck (which is great), however we would need a possibility to download the full file that has changed in order to perform custom diff (like show into a window the original content, and the new one).

I really hope in the future we'll see anything like this!

**Comment by AdriiiPRodri** [comment]
Hi @lucanus81 ,

I see what you say, as you tell us there are different ways to configure **agentless**, in any case we recommend to use a configuration with the agent installed whenever possible. This way we have a more detailed service and more possibilities.

As for the possible configuration of agentless, there are different ways to configure it, in our documentation we have several examples of this: [Agentless examples](https://documentation.wazuh.com/3.x/user-manual/capabilities/agentless-monitoring/agentless-configuration.html#agentless-examples). The limitations of these scripts are described in the link. 

As for the API, we shall discuss the possible addition of this feature for future releases. 
The feature of being able to download the modified file should be studied carefully as it may have implications for the general security of the system. It will be studied along with the possibility of receiving the changes in the API call itself (its depends on the type of file).

Thank you very much for your time and contribution. If you have any other questions, don't hesitate to ask.

Best regards,
Adri

**Comment by lucanus81** [comment]
Adri,

thanks for detailed answer. I think you basically cleared all my doubts :)

best regards,
Luca
