### ISSUE TITLE
Query parameter fails with specials characters

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-api#437]
Hi team,

currently, as indicated in the issue https://github.com/wazuh/wazuh-kibana-app/issues/1709, the parameter to perform queries from the API fails when we include characters like **'/', '\\', etc**. An example of this would be the following call:
```bash
curl -u foo:bar "http://localhost:55000/agents?q=os.name=Debian/Buster"
{"error":622,"message":"Param not valid. Review queries documentation: https://documentation.wazuh.com/current/user-manual/api/queries.html.  Field: q"}
```

In such a way that we will not be able to make this query due to this error.

To solve this we should modify the following regular expression [/api/helpers/input_validation.js#L92](https://github.com/wazuh/wazuh-api/blob/3a5361900219d2972a2e679cd28cbeaffb624609/helpers/input_validation.js#L92). This checks that the entry is correct. The simplest solution would be to add all the invalid characters, for example the characters / and \:

```bash
^(?:\(*[\w\.\-]+(?:=|!=|<|>|~)[\w\.\- \/\\]+\)*)(?:(?:;|,)\(*[\w\.\-]+(?:=|!=|<|>|~)[\w\.\- ]+\)*)*$
```
Another possible solution is to send this character as a **coded character (/ == %2F)**, in this solution we would also have to modify the regular expression to be able to send the modified characters.

Best regards,
Adri

**Comment by davidjiglesias** [comment]
Fixed in https://github.com/wazuh/wazuh/issues/4466
