### ISSUE TITLE
Concurrent Agent Registrations Mangle Data - Likely "Thread Safety Fail"

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh-api#44]
Not sure if this is an API or manager issue, but we made the unfortunate mistake of attempting to register ~100 agents at just about _exactly_ the same time. This resulted in dual registrations of the same ID, an inability to resolve keys, and requirement to wipe the offending ID twice from the managers CLI to remove both artifacts, and then re-register each node separately.
This smells from the outside of a missing semaphore or a threadsafe ID dereference somewhere, but the end result can be very unpleasant. We've never run into this before because the Chef runs arent usually done in 100+ concurrent ssh shells making collisions quite likely. We also saw that a number of nodes had to be re-run as apparently the API has some limit in how many new keys it can generate at the same time (granted, this is an older AMD system, but still 100 key generations shouldnt cause failures, just longer response times to the registration requests).

**Comment by mgmacias95** [comment]
Hello @sempervictus,

This is a known issue we're currently working to fix (check out https://github.com/wazuh/wazuh/pull/306). The issue https://github.com/wazuh/wazuh-api/issues/26 reported exactly the same problem. 

As a temporary solution, you can enable `ossec-authd` daemon. When it is running, all API requests are  forwarded to `ossec-authd` and it is prepared to receive multiple calls at the same time. The steps to enable `ossec-authd` are explained in [our docs](https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html).

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello again,

This issue has been fixed in our latest release Wazuh 3.1. 

Thank you so much for reporting,
Marta
