### ISSUE TITLE
Feature Request: API endpoint to perform a logtest

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-api#449]
Hi team,

Due to this issue https://github.com/wazuh/wazuh-kibana-app/issues/1434, which is in the near Wazuh app (@wazuh/frontend ) roadmap, we need a new endpoint that giving a log (in string format) responds with the result of the logtest in the format you deem appropriate. Plain text or in an object that allows us, for example, show an interactive tree of all the rules showing the "path" taken by analysisd and highlighting why each rule and decoder matched (so like `ossec-logtest -v` but interactive).

Regards.

**Comment by davidjiglesias** [comment]
Done in https://github.com/wazuh/wazuh/issues/5590
