### ISSUE TITLE
Install_api.sh not install the expected version when executed as specified on the documentation

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh-api#457]
Hello team,

We've detected a non-intuitive behavior on the following command specified on the `install from sources` page in our documentation: 

```java
curl -s -o install_api.sh https://raw.githubusercontent.com/wazuh/wazuh-api/v3.7.2/install_api.sh && bash ./install_api.sh download
```

This command, which is specified to download the API in all versions of our documentation (in this case 3.7) download the installation script form the branch referenced, for example 3.7.2, and runs it, but the script, with the `download` option install the most recent version of the API ([see install.sh](https://github.com/wazuh/wazuh-api/blob/master/install_api.sh#L17)).

That makes the documentation to be wrong and is non-intuitive for the user which, having a custom version on the command URL, would expect to download such version and not the recent one. 

Also, this broke the user installation because the most recent version could not be compatible with the manager one.

May we should change this behavior to make the documentation correct or, at least, modify both, script and documentation in order to give a correct command to the users.

Best regards!

**Comment by davidjiglesias** [comment]
Deprecated in Wazuh v4.0.0, API does not need installation
