### ISSUE TITLE
REST API list all outdated agents throws an error "error": 600 Param not valid. Integer expected.  Field: agent_id 

### ISSUE THREAD

**Issue by michaelhidalgo** [wazuh/wazuh-api#47]
Hi Folks, i'm following the examples from [here](https://documentation.wazuh.com/2.1/user-manual/agents/remote-upgrading/upgrading-agent.html?highlight=upgrade) and according to the documentation, this is the method to get outdated agents: 

`curl -u foo:bar -X GET -k "http://127.0.0.1:55000/agents/outdated?pretty"`

However, when we run it, we get below response:

```
curl -u user:token -X GET -k "https://serverip:portnumber/agents/outdated?pretty"
{

   "error": 600,
   "message": "Param not valid. Integer expected.  Field: agent_id"

}
```

Note that we used surrogate values in below request for example purposes.

Can you please advise what might be wrong here?

**Comment by mgmacias95** [comment]
Hello,

It seems the request `GET /agents/outdated` is not in you API. The API request is located at `/api/controllers/agent.js`. Can you confirm me if the following lines are present in your agents.js file?

https://github.com/wazuh/wazuh-api/blob/5919d1ea358ef13296fb967c95083320cc5ce7c6/controllers/agents.js#L343-L376

Best regards,
Marta

**Comment by michaelhidalgo** [comment]
Gracias Marta, let me check. Was this API method introduced in a latest/newest release?

Thanks.

**Comment by mgmacias95** [comment]
Hello @michaelhidalgo,

Yes, it has been added in the Wazuh v3.0.0 release.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello @michaelhidalgo,

I'm closing this issue. Feel free to reopen it if your problem persists.

Best regards,
Marta

**Comment by michaelhidalgo** [comment]
Alright, thanks @mgmacias95
