### ISSUE TITLE
Invalid XML File. Multiple possible root nodes found.

### ISSUE THREAD

**Issue by Aviv641999** [wazuh/wazuh-api#472]
Hi,
Last week i have updated my wazuh manager api to v3.12.0
After the upgrade i experienced errors while updating my agent.conf file by the wazuh-splunk-app.
I have two parts to the file:

<agent_config os="Windows">
</agent_config>
<agent_config os="Linux">
</agent_config>

This structure is validated by my last api v3.9.4 and now it become to be invalid.
Without the solution of grouping, can this problem be solved?
maybe by adding one root node which define the whole segments to one?
maybe changes in source code needed?

Thanks to all the helpers.

**Comment by Zenidd** [comment]
Hello @Aviv641999,

I would like to know more about your environment details:
- Which Wazuh manager and version are you using?
- Did you install the v3.12 API through sources?

I want to point out that v3.11.3 is the last stable version for Manager and API. v3.12 hasn't been officially released yet. Using the right API - manager version combo should be enough for you to use the centralized configuration features again.

I Hope it helps.

Best regards, JP Sáez

**Comment by Aviv641999** [comment]
By downgrading the environment to v3.11.3 the problem has been solved
