### ISSUE TITLE
Error on wazuh api

### ISSUE THREAD

**Issue by muhammaduzairafendi** [wazuh/wazuh-api#480]
We have installed wazuh plugin on kibana 7.6.0.
When we clicked "wazuh" menu, we got an error "Settings. Error. could not select any API entry".
also another error
"3005 - Wrong protocol being used to connect to the wazuh API"
this is the edition i do in wazuh.yml 
hosts: 
  -   default: 
      password: bar
      port: 55000
      url: "http://localhost"
      user: foo

**Comment by AdriiiPRodri** [comment]
Hi @muhammaduzairafendi,

We apologize for the late response. It seems that the protocol used to access the API through Kibana is not correct. To make sure I would like to know what version of the Wazuh API you have, from version [3.12.0](https://documentation.wazuh.com/3.12/release-notes/release_3_12_0.html#wazuh-api) **HTTPS** was enabled by default. 

To check the API version, please run the following command:
`curl -k -u foo:bar https://localhost:55000/version`

On the other hand, I see you have the version `7.6.0` of Wazuh's APP. However, this version is not compatible with Wazuh `3.12.X`. Depending on the specified version by the previous command, we would also need to update the APP. To do this we should first check the [compatibility matrix](https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana-compatibility-matrix) and follow the next steps to update: [Update Wazuh's APP](https://github.com/wazuh/wazuh-kibana-app#upgrade).

I will be waiting for your reply. If you have any questions about the process, don't hesitate to ask.

Regards

**Comment by davidjiglesias** [comment]
Hello @muhammaduzairafendi ,

I close this issue for inactivity. If you have more questions related to this topic or any other one, I suggest joining our Slack channel and be part of our community: https://wazuh.com/community/join-us-on-slack/

Kind regards,

David J. Iglesias
