### ISSUE TITLE
foo: timestamp out of range for platform time_t

### ISSUE THREAD

**Issue by buzzzo** [wazuh/wazuh-api#481]
Hi 
OS: Centos 7 (virtual appliance)

After upgrading rpm wazuh manager to: wazuh-manager-3.12.0-2.i386
and wazuh-api version is: wazuh-api-3.12.0-1.x86_64

Wazuh kibana app cannot connect anymore to api (gives internal server error)

On api.log I have: 

WazuhAPI 2020-03-30 23:40:23 foo: timestamp out of range for platform time_t
WazuhAPI 2020-03-30 23:40:23 foo: [::ffff:127.0.0.1] GET /manager/info? - 200 - error: '1000'.
WazuhAPI 2020-03-30 23:41:42 foo: timestamp out of range for platform time_t
WazuhAPI 2020-03-30 23:41:42 foo: [::ffff:127.0.0.1] GET /manager/info? - 200 - error: '1000'.

**Comment by buzzzo** [comment]
Maybe i've found the issue:

For some strange reason (maybe misconfigured rpm?) yum update have replaced the wazuh-api-3.12.0-1.x86_64 package with wazuh-manager-3.12.0-2.i386.

Please double check your rpm build process as this can create big issue on people without backups.

Thx

**Comment by AdriiiPRodri** [comment]
Hi @buzzzo,

That is right. Apparently, there was some type of problem with the 3.12 packages, we apologize for the inconvenience. You can see more information here: https://wazuh.slack.com/archives/C0A933R8E/p1586871869440800

If you have any questions, please do not hesitate to ask. I give you the links to our mailing list and our slack channel as these will help you more quickly.

- [Mailing list](https://groups.google.com/forum/#!forum/wazuh)
- [Slack](https://wazuh.com/community/join-us-on-slack/)

Best regards,
Adrián Peña
