### ISSUE TITLE
Add support for querying vulnerability data for agent

### ISSUE THREAD

**Issue by binyamz** [wazuh/wazuh-api#488]
Similar to the the SCA REST end point, would help to have similar end point to get vulnerability list for a given agent. In the response payload, would help to include last scan time/evaluation time for the agent.

/vuls/:agent_id

**Comment by AdriiiPRodri** [comment]
Hello @binyamz,

The API does not have this endpoint at the moment. Related endpoints to the vulnerability detector are being developed in the following issue: https://github.com/wazuh/wazuh/issues/3687

Currently we are working on improving the vulnerability detector and subsequently these endpoints will be added.

Regards

**Comment by davidjiglesias** [comment]
Hello @binyamz,

I close this issue for inactivity. If you have more questions related to this topic or any other one, I suggest joining our Slack channel and be part of our community: https://wazuh.com/community/join-us-on-slack/

Kind regards,

David J. Iglesias

**Comment by bkpatientco** [comment]
Whats the status on this?
