### ISSUE TITLE
How can i get alerts from API or other method if it possible

### ISSUE THREAD

**Issue by msalekmouad** [wazuh/wazuh-api#489]
Hello I'm really looking for how to get alerts , security events or file integrity events from API or socket or anithing i can use in other web interface

**Comment by vicferpoy** [comment]
Hello @msalekmouad .

You can take a look at our API reference documentation: https://documentation.wazuh.com/3.12/user-manual/api/reference.html

There you will find all our API endpoints well documented and with examples.

As for the ones you asked for:
- [Get alert or event information about a specific node](https://documentation.wazuh.com/3.12/user-manual/api/reference.html#get-node-node-id-s-stats)
- [FIM related endpoints](https://documentation.wazuh.com/3.12/user-manual/api/reference.html#syscheck)

I hope this helps. If you have any other doubt, don't hesitate to ask.

Regards,
Víctor.

**Comment by vicferpoy** [comment]
Hello again @msalekmouad .

Let me apologize for my last response. I missunderstood you.

The Wazuh API does not have any endpoint to do this since alerts are directly indexed into ElasticSearch. To achieve this, you would need to use the **ElasticSearch API**. You could use **Kibana** and the **Wazuh User Interface (WUI)** to get this information manually, but I believe you want to automate this process.


To get these alerts using the ElasticSearch API, you must use the `_search` endpoint like this (keeping in mind that I have ES in the port 9200):

```
curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts*/_search"
```

That would get you every alert. If you want alerts from a certain day:

```
curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts-3.x-2020.06.03/_search"
```

You can also add queries to filter results. This would be helpful to get the syscheck events you asked for:

```
curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts*/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "query" : {
        "term" : { "rule.groups" : "syscheck" }
    }
}
'
```

You can check more about these API calls here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html

Let us know if this helps and don't hesitate to ask if you have any other doubt.

Regards,
Víctor.

**Comment by msalekmouad** [comment]
Hey , thank you very much thanks I really appreciate , I. Have end of year school project and I really need intrusion detection system so but I 'eed to create my custom web interface also  can you please tell me can wazuh detect attacks ? And what attack I can test when I will be talking in front the jury.
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vicferpoy** [comment]
Hello @msalekmouad ,

Wazuh agents scan the monitored systems looking for malware, rootkits and suspicious anomalies. They can detect hidden files, cloaked processes or unregistered network listeners, as well as inconsistencies in system call responses.

In addition to agent capabilities, the server component uses a signature-based approach to intrusion detection, using its regular expression engine to analyze collected log data and look for indicators of compromise.

You can use our documentation and blogs to learn more about Wazuh intrusion detection. Here you can find some examples:
- [Detecting threats using inventory data](https://wazuh.com/blog/detecting-threats-using-inventory-data/)
- [Detect an SSH brute force attack](https://documentation.wazuh.com/3.12/learning-wazuh/ssh-brute-force.html)
- [Detect an RDP brute force attack](https://documentation.wazuh.com/3.12/learning-wazuh/rdp-brute-force.html)
- [Catch suspicious network traffic](https://documentation.wazuh.com/3.12/learning-wazuh/suricata.html)

I believe these links contain the information you are looking for.

Kind regards,
Víctor.

**Comment by msalekmouad** [comment]
Hello,
Thank you very much.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jasgggit** [comment]
Thank you !! @vicferpoy

**Comment by owais-963** [comment]
@vicferpoy 
```
curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts*/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "query" : {
        "term" : { "rule.groups" : "syscheck" }
    }
}
'
```
this endpoint return only system logs agent ID 000

**Comment by shehryar005** [comment]
> [@vicferpoy](https://github.com/vicferpoy)
> 
> ```
> curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts*/_search?pretty" -H 'Content-Type: application/json' -d'
> {
>     "query" : {
>         "term" : { "rule.groups" : "syscheck" }
>     }
> }
> '
> ```
> 
> this endpoint returns only system logs agent ID 000 I am looking for security events for all agents of a particular group. can you please help me with how can I achieve this?

I'm also working on this if anyone have knowledge guide me!
