### ISSUE TITLE
When trying to restart Agents in a Group without Agents assigned to it shows "Bad request" message.

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh-api#499]
Hello team,
There's an issue when trying to restart Agents from a group which has no Agents assigned to it throught the API. It shows status code 400 along with next detail: 
```
{
  "title": "Bad Request",
  "detail": "The group does not have any agent assigned",
  "remediation": "Please select another group or assign any agent to it",
  "dapi_errors": {
    "wazuh-master": {
      "error": "The group does not have any agent assigned"
    }
  },
  "error": 1755
}
```
- The 3.x API almost always returned a "status code 200" so you had to read the error to know something went wrong.
- This can be seen as an actual bug: sending a group restart request to a server that doesn’t have any agents assigned is not a bad request. If someone has 50+ wazuh servers most surely he/she won't want to have to search for Agents in groups on servers (to find out where the agents are) before sending the restart requests. Instead it'll be preferred to send restart requests to all servers and then collect the affected_ids in the results.
- This issue relates specifically to `PUT /agents/group/{group-name}/restart` endpoint.

**Comment by vicferpoy** [comment]
I'm closing this as this bug happens from `4.x` on. New issue: https://github.com/wazuh/wazuh/issues/8001
