### ISSUE TITLE
Option to provide a CA cert

### ISSUE THREAD

**Issue by TamalSaha** [wazuh/wazuh-api#5]
Hi,
I am working on getting ossec wazuh running inside a Kubernetes cluster. Inside Kubernetes we use a self-signed certificate. We need to a way to pass the ca cert to the api server. I added a commit like 
https://github.com/appscode/wazuh-API/commit/ddf951acdefbedea996670c49e694b94482f42ef

in my fork. Can this be supported here, so that I can delete my fork? 

Thanks.

**Comment by rodrigoDiazAlfaraz** [comment]
Hello @TamalSaha,

Currently, we are studying the best way to add this functionality. We really appreciate your idea and as soon as we fix it, we will let you know.

Thank you so much,
Regards.

**Comment by rodrigoDiazAlfaraz** [comment]
Hello @TamalSaha,

Thank you for your colaboration. Now this functionality is available in the [development branch](https://github.com/wazuh/wazuh-api/commit/82b3bca5a0d16300830b87ac9d4a7d64644f344e).


Thanks,
Regards.

**Comment by TamalSaha** [comment]
Awesome. Thanks!
