### ISSUE TITLE
"Could not connect with Wazuh API. Error: socket hang up. Please, check the URL at settings tab."

### ISSUE THREAD

**Issue by stephenh1991** [wazuh/wazuh-api#6]
Hi,

Not sure if this is API or Manager related. However, we've been using Wazuh v2.0 for about 2 weeks now and today when we loaded up the manager logs page in the app we were greeted the the above kibana error.

The full Kibana log shows this:
{"type":"log","@timestamp":"2017-03-23T13:44:59Z","tags":["\u001b[34mwazuh\u001b[39m","client","error"],"pid":6744,"message":"Could not connect with Wazuh API. Error: socket hang up. Please, check the URL at settings tab."}

The API log when tailed at the same time shows this:

WazuhAPI 2017-03-23 13:44:54: [::ffff:127.0.0.1] GET /manager/logs? - 200 - error: '0'.
WazuhAPI 2017-03-23 13:44:54: [::ffff:127.0.0.1] GET /manager/logs?offset=0&limit=250 - 200 - error: '0'.
WazuhAPI 2017-03-23 13:44:59: [::ffff:127.0.0.1] GET /manager/logs/summary? - 200 - error: '0'.

Whereas the successful attempt looks like this:

WazuhAPI 2017-03-23 13:47:00: [::ffff:127.0.0.1] GET /manager/logs?offset=0&limit=250 - 200 - error: '0'.
WazuhAPI 2017-03-23 13:47:00: [::ffff:127.0.0.1] GET /manager/logs/summary? - 200 - error: '0'.
WazuhAPI 2017-03-23 13:47:00: [::ffff:127.0.0.1] GET /manager/logs?category=all&type_log=all&offset=0&limit=250 - 200                                                                                                                         - error: '0'.
WazuhAPI 2017-03-23 13:47:09: [::ffff:127.0.0.1] GET /manager/logs?category=all&type_log=all&offset=101&limit=250 - 2                                                                                                                        00 - error: '0'.
WazuhAPI 2017-03-23 13:47:10: [::ffff:127.0.0.1] GET /manager/logs?category=all&type_log=all&offset=0&limit=250 - 200                                                                                                                         - error: '0'.

So it looks as if the API response maybe hangs?

The way we fixed this was to move the current ossec.log file to ossec.log.bak and restart the manager to generate a clean log file.

This fixed the issue for us and maybe shows that once the log file grows to a certain size the api call from the Kibana app times out.

Not sure which it may be but if you need more logs let me know :) 

Thanks,
Steve

**Comment by snaow** [comment]
Hi @stephenh1991,

Thanks so much for your feedback, we are studying this issue, seems like we have a couple of timeouts which are preventing the request to sent back the response properly.
The API has a timeout of 30s, the App has a timeout of 5s.

_/manager/logs/summary_ request was taking too much time for large _ossec.log_ files, we [added](4b3ae61e57abdab6b41bc5fd4b138ac23c11dbe6) a lines count limit to prevent the operations to take too much time.
The summary request will gather by default three months back of data or 50.000 lines as maximum.

We also added a [configuration file](615b4cb828aa3d7caa66175db264959e01b5209f) in Wazuh App, with a new setting _timeout_, set by default to 5s, but it could be modified by the user.

Two fixes will be available on next versions.

Thanks again for your feedback, feel free to tell us any other issue you encounter.
Regards,
Pedro.

**Comment by stephenh1991** [comment]
Thanks Pedro!

Makes sense, for now we've just got a cron job which truncates the log weekly into a backup file to keep it small. Will lookout for this in the next release :) 

Cheers,
Steve
