### ISSUE TITLE
"Manager - Status: Unexpected error. Please, report this error." with wrong permissions

### ISSUE THREAD

**Issue by cfi-gb** [wazuh/wazuh-api#62]
wazuh-manager: 3.1.0
wazuh-api: 3.1.0

Hi,

i tested a few local rules and decoders in the scope of https://github.com/wazuh/wazuh-ruleset/pull/102 . After those changes i've noticed that opening the "status" page within the Wazuh Kibana App the following error is shown without giving any information about the reason:

``
Manager - Status: Unexpected error. Please, report this error.
``

The only hint i've found was within the api.log:

``
WazuhAPI 2018-02-11 20:34:33: [::ffff:192.168.0.1] GET /decoders/?offset=0&limit=1 - 200 - error: '1501'.
``

which has lead me to the changes to the decoder i had done today. And indeed the decoder had wrong permissions like:

``
-rw-r----- 1 root root   4301 Feb 11 16:49 0450-openvas_decoders.xml
``

instead of the expected:

``
-rw-r----- 1 root ossec   4301 Feb 11 16:49 0450-openvas_decoders.xml
``

I think catching this "1501" error in some way and making the user aware that there might be some permission errors might be useful instead of the plain "Unexpected error" currently thrown.

**Comment by JuanjiJG** [comment]
Hi @cfi-gb,

Thanks for your feedback. The Wazuh App team have been working on several improvements to the error handler and the way errors are thrown, showing them to the user as a notification on the app. These improvements are available on the latest version of the app, but maybe some error codes have been left behind.

Just to be sure, could you please tell me what's the app version you have currently installed? You can check it out by opening the `package.json` file, usually located at:

`/usr/share/kibana/plugins/wazuh/package.json`

And look at the `revision` field. Please, paste here the value. Thanks for your patience and collaboration.

Best regards,
Juanjo

**Comment by cfi-gb** [comment]
Hi @JuanjiJG,

thanks for your response. I'm currently running the following version of kibana and the wazuh-kibana-app:

```
{
  "name": "wazuh",
  "version": "3.1.0",
  "revision": "0377",
  "kibana": {
    "version": "6.1.2"
  },
```

Looks like there is a new version 6.1.3 of kibana and a new 3.2.0 version of the wazuh app available since a few days so i try to update to those first.

**Comment by jesusgn90** [comment]
Hi @cfi-gb you are right, we have a new release, but it's not avalaible to all wazuh components just now, we are planning to  publish in the next days, so you should wait to fully released all the wazuh components. Any way you could give a try to our package for 3.1.0 with Elastic 6.1.2 but revision 380 not 377. To make it right, please follow these commands:

Assuming that you've installed it from packages, it usually is located on `/usr/share/kibana/`:

```
# systemctl stop kibana
# /usr/share/kibana/bin/kibana-plugin remove wazuh
# rm -rf /usr/share/kibana/optimize/bundles
# export NODE_OPTIONS="--max-old-space-size=3072"
# /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.1.0_6.1.2.zip
```

Once Wazuh 3.2.0 is published you could update all Wazuh components. Also I want to tell you that we will have package for 3.2.0-6.1.2 and 3.2.0-6.2.x as well. This way you will be free to upgrade or not your Elasticsearch environment.

One more time, thanks for your feedback and have a nice day.

King regards,
Jesús

**Comment by cfi-gb** [comment]
@JuanjiJG @jesusgn90 Thanks again to both of you for the background / help. I've updated to Wazuh 3.2.0 and ELK 6.2.x and the new message on wrong permissions is now:

``
Manager. Error. Error reading decoder files: 0450-openvas_decoders.xml. Error: [Errno 13] Permission denied: '/var/ossec/ruleset/decoders/0450-openvas_decoders.xml'
``

Great improvement 👍

**Comment by JuanjiJG** [comment]
Hi @cfi-gb,

We're glad you like the improvements! The team always appreciates your feedback. Don't hesitate to post a new issue if you have more problems related to Wazuh or the Wazuh App.

Regards,
Juanjo
