### ISSUE TITLE
IE has not had it's initial startup dialogue dismissed, please complete this step and try again. Script will exit. Error: Please Run OSSEC_AgentConfig Separately once you correct the error.

### ISSUE THREAD

**Issue by hermespecter** [wazuh/wazuh-api#73]
I get this error when i try to run 'api-register-agent.ps1'. 

Pls advice

**Comment by jesuslinares** [comment]
Hi @hermespecter ,

It's been almost a month since the last response to this issue, so I'll proceed to close it.

Don't hesitate to open a new one if you still have questions.

Thanks,
Jesus.
