### ISSUE TITLE
GET /agents/groups/:group_id broken when sorting

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-api#75]
Hi , 

**GET /agents/groups/:group_id** route returns the following error message when '?sort=' argument is used with any value:

```
{"error":1000,"message":"Wazuh-Python Internal Error: 'set' object has no attribute '__getitem__'"}
```

Thanks team

**Comment by mgmacias95** [comment]
Hello @manuasir,

This bug was fixed in https://github.com/wazuh/wazuh/commit/3d0308d32c2724061930e06631467ae721c0a02b.

Best regards,
Marta

**Comment by manuasir** [comment]
Nice job @mgmacias95
