### ISSUE TITLE
Agents purging - Never Connected status

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh-api#79]
Current request `POST:/agents/purge` is removing _never connected_ agents, the ones could be agents registered recently and pending to report data.

The purge is based on _timeframe_ value which can not be applied to non connected agents, that is why we should add a new flag to force/decide when to remove those agents.

**Comment by jesuslinares** [comment]
The new requests would be:

- DELETE /agents/purge/disconnected?timeframe=1d
- DELETE /agents/purge/neverconnected
- DELETE /agents/purge?timeframe=1d
  - It removes both disconnected and never connected
  - The timeframe doesn't apply for never connected

**Comment by jesuslinares** [comment]
This looks better:

Replace `POST /agents/purge` for:
  -  DELETE /agents
  -  DELETE /agents/:agent_id
  -  DELETE /agents?status=active
  -  DELETE /agents?status=disconnected
  -  DELETE /agents?status=disconnected&timeframe=1d
  -  DELETE /agents?status=neverconnected
  -  DELETE /agents?status=neverconnected&timeframe=1d (is this possible?)

Replace `GET /agents/purgeable/:timeframe` for:
  -  GET /agents?status=active|disconnected|nerverconnected
  -  GET /agents?status=disconnected|neverconnected&**timeframe=1d**
