### ISSUE TITLE
Need more accepted characters

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#80]
Hello team, this API is awesome but we have some limitations regarding to accepted characters. I know it could be weird and we can't accept all kind of character but it would be nice if we add characters like à,è,á,é, etc. French users will agree with this.

Regards,
Jesús

**Comment by JuanjiJG** [comment]
Hello team,

I would like to add that the `ñ`, `ç` and `€` characters aren't also accepted by the API.

Regards,
Juanjo

**Comment by jesuslinares** [comment]
Since everything ends in the framework, we can change the current validations:

- API level: Just filter dangerous characters: ;, |, &, ', etc.
- Framework level: Perform the semantic validation like "only numbers for agent ID".
