### ISSUE TITLE
Respect searching starting by zero

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#81]
Hello team, what I meant with the title is the next scenario:

- If my search is using "002" you are using 2, I think because you are parsing to integer or something similar. But if I search for "002" maybe I'm looking for specific items not all items whose include 2.

From my view this shouldn't be so hard to fix and makes sense. 

Regards,
Jesús

**Comment by mgmacias95** [comment]
Hello @jesusgn90,

This error has been fixed in https://github.com/wazuh/wazuh/pull/653. We have added an extra search to make sure the results match exactly with the requested value. This only affects the `GET/agents` API call.

Best regards,
Marta

**Comment by jesusgn90** [comment]
OK @mgmacias95 and @Lifka , thanks!

Regards,
Jesús
