### ISSUE TITLE
Get CIS-CAT scan information from Wazuh DB

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-api#87]
Hi team, 

Since this commit: [0a8cf7be7d28dc121f2c13c33a12868f51b23c23](https://github.com/wazuh/wazuh/pull/658/commits/0a8cf7be7d28dc121f2c13c33a12868f51b23c23)
 there exists a new table in the agents' databases to store the CIS-CAT stats of the scans.

For Wazuh v3.3.0,  we would new a new API call to retrieve that data from the DB.

Thanks!

**Comment by mgmacias95** [comment]
Done in #142 .
