### ISSUE TITLE
Exclude option

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#93]
Hello team, it's not enough to use negated search, we need an excluding option.

- Using negated search could not work as expected.
- Using excluding option by specific field should work always as expected.

This way the negated search should be still available but the excluding option should work as follow:

- Given a route which returns an array of items /agents
  - It would be nice if I can say "give me all the agents except agents whose OS is CentOS 7"

Regards,
Jesús

**Comment by jesuslinares** [comment]
This feature will be covered with the "filter" param:

  `/agents?filter=os.platform ne CentOS7`

More information: https://github.com/wazuh/wazuh-api/issues/110.

Thanks!

**Comment by jesusgn90** [comment]
Oh, looks good to me, I'll track https://github.com/wazuh/wazuh-api/issues/110
